INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (1, 'Alvaro', 1, 1, 1, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (2, 'Alvaro', 1, 1, 2, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (3, 'Carlos', 1, 1, 3, No usé IA para esta tarea porque solo tuve que tocar pequeñas configuraciones que me dijeron);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (4, 'Carmen', 1, 1, 4, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (5, 'Cristian', 1, 1, 5, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (6, 'Cristian', 1, 1, 6, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (7, 'Cristian', 1, 1, 7, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (8, 'Daniel', 1, 1, 8, No aplica ya que se trata añadir endpoints a la propia securización ya existente.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (9, 'Daniel', 1, 1, 9, No aplica debido a que había que identificar que endpoints eran necesario securizar.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (10, 'Fernando', 1, 1, 10, Hacer test en una clase abstracta la instancia. Luego llama a un atributo como si fuera un método, y me sugiere cambiar el código. Análisis código, muy lineal, me comenta línea a línea, no me aporta mucho. Respecto a HU, cuando la tarea es compleja y abarca muchas cosas, la definición también tiene que serlo.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (11, 'Mario', 1, 1, 11, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (12, 'Mario', 1, 1, 12, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (13, 'Mario / Andrea', 1, 1, 13, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (14, 'René', 1, 1, 14, En tareas de crear HU, documentar y comprensión de código muy buenos resultados, pero a la hora de desarrollo de código, no muy buenos resultados en Groovy);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (15, 'Rubén', 1, 1, 15, Es cambiar el nombre del secreto y probar las RIs ya desplegadas, no es necesario el uso de la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (16, 'Rubén', 1, 1, 16, Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (17, 'Rubén', 1, 1, 17, Pasó el análisis kiuwan con todo correcto, por lo que no hizo falta la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (18, 'nan', 1, 1, 18, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (19, 'nan', 1, 1, 19, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (20, 'nan', 1, 1, 20, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (21, 'nan', 1, 1, 21, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (22, 'nan', 1, 1, 22, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (23, 'nan', 1, 1, 23, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (24, 'nan', 1, 1, 24, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (25, 'nan', 1, 1, 25, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (26, 'nan', 1, 1, 26, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (27, 'nan', 1, 1, 27, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (28, 'Andrea', 1, 2, 28, Usada para una primera aproximación de cobertura de pruebas.El resultado es bastante preciso, pero requiere revisión. );
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (29, 'Carlos', 1, 2, 29, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (30, 'Carlos', 1, 2, 30, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (31, 'Daniel', 1, 2, 31, No aplica en este caso.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (32, 'Fernando', 1, 2, 32, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (33, 'Rafa', 1, 2, 33, El cambio a realizar era demasiado evidente y sencillo como para hacer uso de la IA.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (34, 'Rafa', 1, 2, 34, Utilizada para la generación de pruebas con Mockito y Junit);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (35, 'Rafa', 1, 2, 35, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (36, 'René', 1, 2, 36, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (37, 'Rubén', 1, 2, 37, Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (38, 'Rubén', 1, 2, 38, Las respuesta de la IA no era correcta, contrastando información con webs no se podía hacer.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (39, 'Rubén', 1, 2, 39, Aplicada para hacer los test unitarios y refactorizar el código);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (40, 'nan', 1, 2, 40, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (41, 'nan', 1, 2, 41, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (42, 'Alvaro', 1, 3, 42, Se ha utilizado IA para facilitar la realización de los tests.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (43, 'Andrea', 1, 3, 43, Se ha utilizado para extraer cobertura, ha requerido revisión y modificación.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (44, 'Andrea', 1, 3, 44, Se ha utlizado la IA para que proporcione información y detalle acerca del funcionacimiento de la BBDD de Mongo como cache, se preguntan detalles acerca de campos y tipos de datos usados en Mongo DB.Ha permitido aclarar las dudas y disponer de mas información y detalle de los campos de la BBDD .);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (45, 'Antoni', 1, 3, 45, Debido a el ambito de la tarea, subiendo a la version 3.3.2 de springboot, no se a podido utilizar ia, ya que no esta esta en sus datos.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (46, 'Carlos', 1, 3, 46, Fue una migración de jdk17 a 21 la cual no tuvo mucha complejidad ni tuvo que tocar código.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (47, 'Carlos', 1, 3, 47, Realmente en esta tarea no he usado IA porque tenía que dividir una RI en dos RIs, por lo que el código ya estaba hecho.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (48, 'Carlos', 1, 3, 48, Me ha servido la IA para ayudarme a enforcar ciertos problemas de la tarea. Creo que la podría haber sacado sin usarla pero me agilizó el trabajo y creo que tardé menos);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (49, 'Carmen', 1, 3, 49, Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (50, 'Carmen', 1, 3, 50, Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (51, 'Carmen', 1, 3, 51, No ha hecho falta el uso de IA ya que la tara solo consistía en desplegar dos RIs de entirex en preproducción);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (52, 'Cristian', 1, 3, 52, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (53, 'Daniel', 1, 3, 53, Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas práctico que desarrollo por lo que no ha sido necesario el uso de la IA.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (54, 'Daniel', 1, 3, 54, Utilizada para refactorización de un trozo de código que lo hace mas legible y sencillo.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (55, 'Fernando', 1, 3, 55, Añadidos nuevos métodos en RequestBytesService y sus test unitarios);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (56, 'Fernando', 1, 3, 56, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (57, 'Rafa', 1, 3, 57, Tests unitarios de las nuevas funcionalidades del RequestService en el framework);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (58, 'Rafa', 1, 3, 58, Inclusión de los reintentos y envío de la DLT en Kafka RequestService);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (59, 'René', 1, 3, 59, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (60, 'Rubén', 1, 3, 60, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (61, 'Rubén', 1, 3, 61, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (62, 'Fernando', 1, 3, 62, El código es muy jerárquico con mucha abastracción. Los prompts están diseñados para desarrollos más sencillos);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (63, 'Andrea', 1, 4, 63, Eran unos defectos que venian del sprint anterior, por lo que ya estaba todo diseño y ejecutado, solo faltaba reprobar la correción de defectos.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (64, 'nan', 1, 4, 64, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (65, 'Daniel', 1, 4, 65, Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas práctico que desarrollo por lo que no ha sido necesario el uso de la IA.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (66, 'nan', 1, 4, 66, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (67, 'nan', 1, 4, 67, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (68, 'René', 1, 4, 68, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (69, 'Andrea', 1, 4, 69, Se ha utilizado para consultar y aclarar los endpoint y para que nos indicara como preparar los juegos de datos, en este caso no ha indicado un comando de windows para generar ficheros de distinto tamaño.Tambien se ha utilizado para ayudarnos a interpretar los logs y que nos pusiera ejemplos );
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (70, 'nan', 1, 4, 70, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (71, 'Álvaro', 1, 4, 71, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (72, 'René', 1, 4, 72, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (73, 'Alejandro', 1, 4, 73, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (74, 'Daniel', 1, 4, 74, Se ha utilizado para ver que camino era el adecuado al utilizar una función dentro del código.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (75, 'Rafa', 1, 4, 75, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (76, 'Carmen', 1, 4, 76, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (77, 'Carmen', 1, 4, 77, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (78, 'Rafa', 1, 4, 78, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (79, 'Rubén', 1, 4, 79, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (80, 'nan', 1, 4, 80, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (81, 'Álvaro', 1, 4, 81, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (82, 'nan', 1, 4, 82, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (83, 'Rafa', 1, 4, 83, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (84, 'Alejandro', 1, 4, 84, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (85, 'Fernando', 1, 4, 85, Cuando el código aumenta en abastracción y jerarquí se necesitan prompts/modelos más potentes);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (86, 'Carlos / Antoni / Alvaro', 1, 4, 86, No usa IA ya que solo hay que cambiar la versión de las RIs y desplegar);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (87, 'Carlos', 1, 4, 87, Fue util para entender el código y resolver ciertas dudas en general. Me ayudó mucho a generar los tests Unitarios. Aunque al principio costó que me diese la respuesta, tengo que reconocer que sin su ayuda quizás no lo hubiese conseguido y habría obtado por desistir.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (88, 'Álvaro', 1, 4, 88, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (89, 'Daniel', 1, 4, 89, Una tarea de investigación la cual se tenía previamente enlaces de interés en los que venía varias soluciones que se trataron y solucionaron el problema, por lo que no hizo falta el uso de IA.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (90, 'Daniel', 1, 5, 90, Se hizo uso de IA en la documentación del código y en las pruebas unitarias, aunque el resultado no fue completamente el deseado. Haciendo falta algunas anotaciones o parte del código en específico para que realmente funcionase, ofreciendo valores inexistentes o también erróneos lo cual podruce mas confusión que ayudar, pero resolviendolo puede llegar ahorrar algo de tiempo, también documentando el código de una forma muy breve y no tan concisa en los javadocs.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (91, 'Daniel', 1, 5, 91, No se ha usado porque se conocía la causa y una posible viabilidad.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (92, 'Rubén', 1, 5, 92, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (93, 'Rubén', 1, 5, 93, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (94, 'Rubén', 1, 5, 94, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (95, 'Andrea', 1, 5, 95, Utilizada la IA para la ocbertura de casos de prueba, los resultados son bastantes correctos, sobre todo tiene en cuenta los tipos de filtros que se pueden aplicar en el filtrado, y aparte se han realizado consultas sobre el tipo de filtros, su explicacion  y como funcionan en la aplicación S3 lo que ha dado una respuesta bastante aclaratoria y precisa);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (96, 'Daniel', 1, 5, 96, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (97, 'Daniel', 1, 5, 97, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (98, 'Fernando', 1, 5, 98, Utilizada para Test y para comprender el uso de métricas);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (99, 'René', 1, 5, 99, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (100, 'Alejandro', 1, 5, 100, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (101, 'Antoni', 1, 5, 101, Se ha aplicado la IA de forma satisfactoria en la creación de scripts destinados a modificar ciertos fragmentos de codigo,  y con un poco de ayuda y correcciones, ha sabido proporcionar el resultado esperado, acelerando el desarrollo de estos scripts.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (102, 'nan', 1, 5, 102, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (103, 'Alvaro', 1, 5, 103, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (104, 'Carlos', 1, 5, 104, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (105, 'Carlos', 1, 5, 105, Para esta tarea no necesité IA porque realmente era darse cuenta de que los drivers estaban desactualizados para la nueva versión de Spring Boot y era necesario solamente actualizarlos.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (106, 'Andrea', 1, 5, 106, Para la ejecución manual de los test no automatizados no se ha requerido el uso de la IA, ya que los test ejecutados ya habían sido previamente diseñados y ejecutados en otros sprints);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (107, 'Cristian', 1, 5, 107, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (108, 'nan', 1, 5, 108, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (109, 'Rafa', 1, 5, 109, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (110, 'Rafa', 1, 5, 110, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (111, 'nan', 1, 5, 111, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (112, 'Carmen', 1, 5, 112, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (113, 'Carmen', 1, 5, 113, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (114, 'Alejandro', 1, 5, 114, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (115, 'Andrea', 1, 5, 115, Se usa para la IA cobertura de pruebas y para realizar consultas de los posibles motivos de que se muestren interrogaciones en lugar de tildes en la BBDD cuando carga un fichero de empleados.El resultado es bastante preciso y acertado, pero en el caso de la cobertura es necesario realizar alguna modificación y ajuste);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (116, 'Cristian', 1, 5, 116, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (117, 'Mario', 1, 5, 117, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (118, 'Rubén', 1, 5, 118, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (119, 'nan', 1, 5, 119, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (120, 'Alejandro', 1, 5, 120, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (121, 'Antoni', 1, 6, 121, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (122, 'Antoni', 1, 6, 122, Debido al tipo de correcciones a realizar, no ha sido necesario el uso de la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (123, 'Antoni', 1, 6, 123, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (124, 'Rafa', 1, 6, 124, La tarea principal consistía en analizar cómo añadir en el framework una nueva feature y la IA fue útil para consultar pequeños detalles);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (125, 'Rubén', 1, 6, 125, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (126, 'Rubén', 1, 6, 126, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (127, 'Rubén', 1, 6, 127, Constaba de probar las RIs en integración por lo que no es necesario el uso de la IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (128, 'Rafa', 1, 6, 128, En esta tarea he utilizado muchísimo la IA para lenvantar la consola y registrar las aplicaciones dentro.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (129, 'Daniel', 1, 6, 129, Aplica lo mismo que en el análisis, no se ha usado porque se conocía la causa y una posible viabilidad.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (130, 'Daniel', 1, 6, 130, Se facilitaron docs y comentarios para resolver este problema.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (131, 'Daniel', 1, 6, 131, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (132, 'Carlos', 1, 6, 132, Usé realmente la IA para los tests unitarios);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (133, 'René', 1, 6, 133, IA utilizada para algunas partes del analisis realizado, pero no aplica uso de los prompts existentes);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (134, 'René', 1, 6, 134, IA utilizada para dudas en código groovy,pero no aplica el uso de prompts existentes);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (135, 'Carmen', 1, 6, 135, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (136, 'Carmen', 1, 6, 136, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (137, 'Andrea', 1, 6, 137, Usada IA para aclaración y explicación de unas cabeceras obtenidas en un microservicio en el campo Curl.Explicación, aclaración y matices necesarios de campo Curl de las cabeceras H 'accept: application/octet-stream' y H 'accept: image/jpeg');
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (138, 'Mario ', 1, 6, 138, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (139, 'Mario ', 1, 6, 139, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (140, 'Andrea', 1, 6, 140, Creación de HU usando IA , el resultado es bastante preciso y correcto, se necesitan hacer algunas modificaciones ya que en algun punto no llega a aclarar  o explicar bien lo que se pide en la HU, se añaden modificaciones para explicar mejor los criterios de aceptacion.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (141, 'Fernando', 1, 6, 141, Analisis de las salidas de prometheus. Petición de algoritmo.  Test (36 hoaras con ira, 40 sin IA));
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (142, 'Daniel', 1, 7, 142, Gracias a las documentaciones que tenía a mano no necesité usar en este caso la IA.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (143, 'Carlos', 1, 7, 143, No he necesitado IA. Solo documentación y mirar ejemplos);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (144, 'Andrea', 1, 7, 144, No se ha necesitado IA ya que estan tareas correspondian a ejecución de pruebas );
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (145, 'Andrea', 1, 7, 145, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (146, 'nan', 1, 7, 146, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (147, 'nan', 1, 7, 147, Tarea de pruebas, no aplica IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (148, 'nan', 1, 7, 148, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (149, 'nan', 1, 7, 149, Tarea de soporte para crear una nu8eva pipeline en jenkins, no aplica IA);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (150, 'Carmen', 1, 7, 150, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (151, 'Carmen', 1, 7, 151, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (152, 'nan', 1, 7, 152, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (153, 'nan', 1, 7, 153, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (154, 'Ruben', 1, 7, 154, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (155, 'Ruben', 1, 7, 155, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (156, 'Ruben', 1, 7, 156, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (157, 'Antoni-Rafa', 1, 7, 157, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (158, 'nan', 1, 7, 158, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (159, 'nan', 1, 7, 159, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (160, 'nan', 1, 7, 160, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (161, 'nan', 1, 7, 161, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (162, 'Carlos', 1, 7, 162, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (163, 'Rafa', 1, 7, 163, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (164, 'Ruben', 1, 7, 164, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (165, 'nan', 1, 7, 165, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (166, 'nan', 1, 7, 166, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (167, 'nan', 1, 7, 167, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (168, 'nan', 1, 7, 168, Inframail no soporta HTML, por lo que el uso de IA no ha hecho falta aquí debido a que se solicitó soporte al propio equipo dando esta conclusión.);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (169, 'nan', 1, 7, 169, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (170, 'nan', 1, 7, 170, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (171, 'nan', 1, 7, 171, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (172, 'nan', 1, 7, 172, nan);
INSERT INTO estimacion (id, owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (173, 'nan', 1, 7, 173, nan);
