INSERT INTO prompt (id, prompt, proyecto_id) VALUES (1, 'Documentar', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (2, 'Refactorizar', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (3, 'Comprender Codigo Fuente', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (4, 'Analisis Desa APIs', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (5, 'Pruebas Unitarias', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (6, 'Pruebas Funcionales', 1);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (7, 'Documentar', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (8, 'Refactorizar', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (9, 'Comprender Codigo Fuente', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (10, 'Analisis Desa APIs', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (11, 'Pruebas Unitarias', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (12, 'Pruebas Funcionales', 2);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (13, 'Documentar', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (14, 'Refactorizar', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (15, 'Comprender Codigo Fuente', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (16, 'Analisis Desa APIs', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (17, 'Pruebas Unitarias', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (18, 'Pruebas Funcionales', 3);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (19, 'Documentar', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (20, 'Refactorizar', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (21, 'Comprender Codigo Fuente', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (22, 'Analisis Desa APIs', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (23, 'Pruebas Unitarias', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (24, 'Pruebas Funcionales', 4);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (25, 'Documentar', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (26, 'Refactorizar', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (27, 'Comprender Codigo Fuente', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (28, 'Analisis Desa APIs', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (29, 'Pruebas Unitarias', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (30, 'Pruebas Funcionales', 6);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (31, 'Documentar', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (32, 'Refactorizar', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (33, 'Comprender Codigo Fuente', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (34, 'Analisis Desa APIs', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (35, 'Pruebas Unitarias', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (36, 'Pruebas Funcionales', 8);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (37, 'Documentar', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (38, 'Refactorizar', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (39, 'Comprender Codigo Fuente', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (40, 'Analisis Desa APIs', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (41, 'Pruebas Unitarias', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (42, 'Pruebas Funcionales', 9);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (43, 'Documentar', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (44, 'Refactorizar', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (45, 'Comprender Codigo Fuente', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (46, 'Analisis Desa APIs', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (47, 'Pruebas Unitarias', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (48, 'Pruebas Funcionales', 10);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (49, 'Documentar', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (50, 'Refactorizar', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (51, 'Comprender Codigo Fuente', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (52, 'Analisis Desa APIs', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (53, 'Pruebas Unitarias', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (54, 'Pruebas Funcionales', 11);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (55, 'Documentar', 12);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (56, 'Refactorizar', 13);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (57, 'Compren.Cod.Fuente', 12);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (58, 'Análisis Desa APIs', 14);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (59, 'Pruebas Unitarias', 13);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (60, 'Pruebas Funcionales', 13);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (61, 'Documentar', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (62, 'Refactorizar', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (63, 'Comprender Codigo Fuente', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (64, 'Analisis Desa APIs', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (65, 'Pruebas Unitarias', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (66, 'Pruebas Funcionales', 15);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (67, 'Documentar', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (68, 'Refactorizar', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (69, 'Comprender Codigo Fuente', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (70, 'Analisis Desa APIs', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (71, 'Pruebas Unitarias', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (72, 'Pruebas Funcionales', 16);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (73, 'Documentar', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (74, 'Refactorizar', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (75, 'Comprender Codigo Fuente', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (76, 'Analisis Desa APIs', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (77, 'Pruebas Unitarias', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (78, 'Pruebas Funcionales', 22);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (79, 'T02_Diseño de Casos de Prueba', 26);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (80, 'T03_Combinación de Datos de Prueba', 26);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (81, 'T04_Plan de Pruebas de Regresión', 26);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (82, 'T05_Estrategia de pruebas', 26);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (83, 'T06_Scripts de Automatización', 14);
INSERT INTO prompt (id, prompt, proyecto_id) VALUES (84, 'Información para Pruebas (sin Prompt)', 14);
