INSERT INTO proyecto (id, nombre) VALUES (1, 'ABDV');
INSERT INTO proyecto (id, nombre) VALUES (2, 'STAG');
INSERT INTO proyecto (id, nombre) VALUES (3, 'GDLC2');
INSERT INTO proyecto (id, nombre) VALUES (4, 'DEVOPS');
INSERT INTO proyecto (id, nombre) VALUES (5, 'DEVOPS Soporte');
INSERT INTO proyecto (id, nombre) VALUES (6, 'CIDIGA');
INSERT INTO proyecto (id, nombre) VALUES (7, 'CIGDOC');
INSERT INTO proyecto (id, nombre) VALUES (8, 'CIDCLO');
INSERT INTO proyecto (id, nombre) VALUES (9, 'EVsCaching');
INSERT INTO proyecto (id, nombre) VALUES (10, 'FDAR');
INSERT INTO proyecto (id, nombre) VALUES (11, 'IBase');
INSERT INTO proyecto (id, nombre) VALUES (12, 'APNA');
INSERT INTO proyecto (id, nombre) VALUES (13, 'Testing');
INSERT INTO proyecto (id, nombre) VALUES (14, 'NAUA');
INSERT INTO proyecto (id, nombre) VALUES (15, 'NAUF');
INSERT INTO proyecto (id, nombre) VALUES (16, 'DEPOLIFE');
INSERT INTO proyecto (id, nombre) VALUES (17, 'DESACITA');
INSERT INTO proyecto (id, nombre) VALUES (18, 'DESACEIN');
INSERT INTO proyecto (id, nombre) VALUES (19, 'DEDIGRAF');
INSERT INTO proyecto (id, nombre) VALUES (20, 'DEPINTRA');
INSERT INTO proyecto (id, nombre) VALUES (21, 'DEPINTE ');
INSERT INTO proyecto (id, nombre) VALUES (22, 'ProsaGen');
INSERT INTO proyecto (id, nombre) VALUES (23, 'WF');
INSERT INTO proyecto (id, nombre) VALUES (24, 'Arquitectura');
INSERT INTO proyecto (id, nombre) VALUES (25, 'PDPR');
INSERT INTO proyecto (id, nombre) VALUES (26, 'PROSA- WORKFLOW');
INSERT INTO proyecto (id, nombre) VALUES (27, 'Plataformas Digitales');
INSERT INTO proyecto (id, nombre) VALUES (28, 'PROSA- PDPR');
INSERT INTO proyecto (id, nombre) VALUES (29, 'PROSA- PROSAGEN');
INSERT INTO proyecto (id, nombre) VALUES (30, 'RRHH');
INSERT INTO proyecto (id, nombre) VALUES (31, 'PDAU-Portales');
INSERT INTO proyecto (id, nombre) VALUES (32, 'IBASE');
INSERT INTO proyecto (id, nombre) VALUES (33, 'PDCF');
INSERT INTO proyecto (id, nombre) VALUES (34, 'PROSA-PROSAGEN');
INSERT INTO proyecto (id, nombre) VALUES (35, 'Digitalización');
INSERT INTO proyecto (id, nombre) VALUES (36, 'PDPR-AUTO');
