INSERT INTO sprint (id, nombre, proyecto_id) VALUES (1, 'SP1', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (2, 'SP2', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (3, 'SP3', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (4, 'SP4', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (5, 'SP5', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (6, 'SP6', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (7, 'SP7', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (8, 'SP0', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (9, 'SP1', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (10, 'SP2', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (11, 'SP3', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (12, 'SP4', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (13, 'SP5', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (14, 'SP6', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (15, 'SP15', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (16, 'SP16', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (17, 'SP17', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (18, 'SP18', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (19, 'SP19', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (20, 'SP20', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (21, 'SP21', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (22, 'SP22', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (23, 'SP40', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (24, 'SP40', 5);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (25, 'SP41', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (26, 'SP42', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (27, 'SP43', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (28, 'SP44', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (29, 'SP45', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (30, 'SP46', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (31, 'SP83 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (32, 'SP91 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (33, 'SP05 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (34, 'SP84 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (35, 'SP92 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (36, 'SP06 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (37, 'SP93 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (38, 'SP85 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (39, 'SP07 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (40, 'SP86 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (41, 'SP94 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (42, 'SP08 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (43, 'SP87 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (44, 'SP95 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (45, 'SP09 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (46, 'SP10 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (47, 'SP96 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (48, 'SP88 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (49, 'SP97 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (50, 'SP9', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (51, 'SP10', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (52, 'SP11', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (53, 'SP12', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (54, 'SP13', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (55, 'SP14', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (56, 'SP15', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (57, 'SP16', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (58, 'nan', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (59, 'SP18', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (60, 'SP13', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (61, 'SP14', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (62, 'SP15', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (63, 'SP16', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (64, 'SP17', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (65, 'SP19', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (66, 'SP20', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (67, 'SP83', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (68, 'SP91', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (69, 'SP05', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (70, 'SP84', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (71, 'SP92', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (72, 'SP06', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (73, 'SP93', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (74, 'SP85', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (75, 'SP07', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (76, 'SP86', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (77, 'SP94', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (78, 'SP08', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (79, 'SP87', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (80, 'SP95', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (81, 'SP09', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (82, 'Octubre', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (83, 'Noviembre', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (84, 'PGEN22', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (85, 'WF 21', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (86, 'ARQ22', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (87, 'PDPR01', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (88, 'WF 22', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (89, 'ARQ23', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (90, 'PDPR02', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (91, 'PGEN23', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (92, 'PGEN24', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (93, 'ARQ24', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (94, 'WF 23', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (95, 'Sprint 20', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (96, 'nan', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (97, 'Sprint 21', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (98, 'Srpint 22', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (99, 'Sprint 23', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (100, 'Sprint 24', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (101, 'SP20', 18);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (102, 'SP20', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (103, 'SP20', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (104, 'SP21', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (105, 'SP21', 18);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (106, 'SP21', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (107, 'SP22', 18);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (108, 'SP22', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (109, 'SP22', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (110, 'SP23', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (111, 'SP23', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (112, 'SP24', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (113, 'SP24', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (114, 'SP24', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (115, 'SP25', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (116, 'SP26', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (117, 'Diciembre', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (118, 'SP20', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (119, 'SP21', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (120, 'SP22', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (121, 'SP23', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (122, 'DEPOLIFE 107', 21);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (123, 'DEPOLIFE 106', 21);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (124, 'DESACITA 100', 22);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (125, 'DESACITA S/P', 22);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (126, 'DESACEIN 115', 23);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (127, 'DESACEIN 116', 23);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (128, 'DEDIGRAF 8', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (129, 'DEDIGRAF 9', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (130, 'DEDIGRAF 10', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (131, 'DEPINTRA 108', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (132, 'DEPINTRA S/P', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (133, 'DEPINTE 102', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (134, 'DEPINTE S/P', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (135, 'PDPR03', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (136, '22', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (137, '22', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (138, '23', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (139, 'T49', 28);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (140, 'Fase 2', 29);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (141, 'T52', 28);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (142, 'T53', 28);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (143, '22', 30);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (144, '23', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (145, '25', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (146, '16', 31);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (147, '17', 31);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (148, '21', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (149, '16', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (150, '24', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (151, '26', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (152, 'T55', 32);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (153, 'TM31', 33);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (154, 'TM30', 33);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (155, '20', 31);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (156, '24', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (157, 'PDCF', 34);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (158, '4', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (159, '23', 35);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (160, '24', 35);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (161, 'T4', 36);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (162, '22', 34);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (163, '4', 37);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (164, 'T54', 32);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (165, '27', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (166, 'TM32', 33);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (167, '25', 35);
