INSERT INTO sprint (id, nombre, proyecto_id) VALUES (1, 'SP1', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (2, 'SP2', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (3, 'SP3', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (4, 'SP4', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (5, 'SP5', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (6, 'SP6', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (7, 'SP7', 1);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (8, 'SP0', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (9, 'SP1', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (10, 'SP2', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (11, 'SP3', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (12, 'SP4', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (13, 'SP5', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (14, 'SP6', 2);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (15, 'SP15', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (16, 'SP16', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (17, 'SP17', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (18, 'SP18', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (19, 'SP19', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (20, 'SP20', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (21, 'SP21', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (22, 'SP22', 3);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (23, 'SP40', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (24, 'SP40', 5);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (25, 'SP41', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (26, 'SP42', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (27, 'SP43', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (28, 'SP44', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (29, 'SP45', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (30, 'SP46', 4);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (31, 'SP83 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (32, 'SP91 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (33, 'SP05 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (34, 'SP84 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (35, 'SP92 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (36, 'SP06 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (37, 'SP93 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (38, 'SP85 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (39, 'SP07 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (40, 'SP86 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (41, 'SP94 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (42, 'SP08 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (43, 'SP87 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (44, 'SP95 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (45, 'SP09 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (46, 'SP10 - NMDE', 8);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (47, 'SP96 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (48, 'SP88 - NOTE', 6);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (49, 'SP97 - GDOC', 7);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (50, 'SP9', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (51, 'SP10', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (52, 'SP11', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (53, 'SP12', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (54, 'SP13', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (55, 'SP14', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (56, 'SP15', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (57, 'SP16', 9);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (58, 'SP13', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (59, 'SP18', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (60, 'SP14', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (61, 'SP15', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (62, 'SP16', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (63, 'SP17', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (64, 'SP19', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (65, 'SP20', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (66, 'Octubre', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (67, 'Noviembre', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (68, 'Diciembre', 11);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (69, 'SP20', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (70, 'SP20', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (71, 'SP20', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (72, 'SP21', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (73, 'SP21', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (74, 'SP21', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (75, 'SP22', 12);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (76, 'SP22', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (77, 'SP22', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (78, 'SP23', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (79, 'SP23', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (80, 'SP24', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (81, 'SP24', 13);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (82, 'SP25', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (83, 'SP26', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (84, 'Sprint 20', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (85, 'Sprint 21', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (86, 'Srpint 22', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (87, 'Sprint 23', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (88, 'Sprint 24', 15);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (89, 'DEPOLIFE 107', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (90, 'DEPOLIFE 106', 16);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (91, 'DESACITA 100', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (92, 'DESACITA S/P', 17);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (93, 'DESACEIN 115', 18);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (94, 'DESACEIN 116', 18);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (95, 'DEDIGRAF 8', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (96, 'DEDIGRAF 9', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (97, 'DEDIGRAF 10', 19);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (98, 'DEPINTRA 108', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (99, 'DEPINTRA S/P', 20);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (100, 'DEPINTE 102', 21);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (101, 'DEPINTE S/P', 21);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (102, 'PGEN22', 22);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (103, 'WF 21', 23);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (104, 'ARQ22', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (105, 'PDPR01', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (106, 'WF 22', 23);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (107, 'ARQ23', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (108, 'PDPR02', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (109, 'PGEN23', 22);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (110, 'PGEN24', 22);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (111, 'ARQ24', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (112, 'WF 23', 23);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (113, 'PDPR03', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (114, '21', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (115, '22', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (116, '22', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (117, '23', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (118, 'T49', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (119, 'Fase 2', 28);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (120, 'T52', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (121, 'T53', 27);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (122, '22', 29);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (123, '23', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (124, '25', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (125, '16', 30);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (126, '17', 30);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (127, '16', 10);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (128, '24', 24);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (129, '26', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (130, 'T55', 31);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (131, 'TM31', 32);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (132, 'TM30', 32);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (133, '20', 30);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (134, '24', 26);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (135, 'PDCF', 33);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (136, '4', 25);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (137, '23', 34);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (138, '24', 34);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (139, 'T4', 35);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (140, '22', 33);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (141, '4', 36);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (142, 'T54', 31);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (143, '27', 14);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (144, 'TM32', 32);
INSERT INTO sprint (id, nombre, proyecto_id) VALUES (145, '25', 34);
