INSERT INTO tarea (id, descripcion, sprint_id) VALUES (1, 'DENAUA-907 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (2, 'DENAUA-912-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (3, 'DENAUA-916 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (4, 'DENAUA-903 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (5, 'DENAUA-909 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (6, 'DENAUA-910-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (7, 'DENAUA-911-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (8, 'DENAUA-897 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (9, 'DENAUA-914 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (10, 'DENAUA-933-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (11, 'DENAUA-862 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (12, 'DENAUA-864 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (13, 'DENAUA-550 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (14, 'DENAUA-545 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (15, 'DENAUA-904 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (16, 'DENAUA-905 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (17, 'DENAUA-908 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (18, 'DENAUA-919 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (19, 'DENAUA-920 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (20, 'DENAUA-921 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (21, 'DENAUA-923 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (22, 'DENAUA-926 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (23, 'DENAUA-930 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (24, 'DENAUA-932-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (25, 'DENAUA-937-Testing - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (26, 'DENAUA-945 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (27, 'DENAUA-948 - nan', 1);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (28, 'DENAUA-974-Testing - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (29, 'DENAUA-947 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (30, 'DENAUA-973 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (31, 'DENAUA-952 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (32, 'DENAUA-962-Testing - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (33, 'DENAUA-917 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (34, 'DENAUA-949 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (35, 'DENAUA-950 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (36, 'DENAUA-485 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (37, 'DENAUA-545 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (38, 'DENAUA-906 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (39, 'DENAUA-956-Testing - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (40, 'DENAUA-944 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (41, 'DENAUA-946 - nan', 2);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (42, 'DANAUA-618 - [APNA] Actualización NauaCLI a última versión por commandline', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (43, 'DENAUA-1014-Testing - [Testing] Fase II - Pruebas desarrollos RI Cola MQ', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (44, 'DENAUA-1030-Testing  - [Testing] Cobertura, diseños de casos en ALM y Pruebas de operaciones en caché con MongoDb', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (45, 'DENAUA-980 - Subir versión de Spring Boot a la 3.3.2', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (46, 'DENAUA-1015 - [APNA] Fase II - Pruebas Onbo', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (47, 'DENAUA-1029 - Separar la RI  ot_nauamqse_ri-mqseries (productor/consumidor) MQ, en un productor y un consumidor', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (48, 'DENAUA-1034 - Modifiicar la Configuración del componente LongRunningAction para fijar enable-auto-commit a false, max-poll-records a 1', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (49, 'DENAUA-1000 - Fase I - Starter S3: funcionalidades basicas', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (50, 'DENAUA-1009 - Creación de RI con starter S3', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (51, 'DENAUA-975 - Fase II - Pasar RIs EntireX a CER y PRE y crear planes de prueba', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (52, 'DENAUA-957 - [Testing Automatización] Automatizar casos de RestClient', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (53, 'DENAUA-950 - Análisis reenganche de request-reply cuando Kafka cae', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (54, 'DENAUA-988 - Corregir configuración Kafka para comprobar si existe seguridad antes de buscar usuario', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (55, 'DENAUA-1021 - Fase II - Implementación Long Running Kafka', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (56, 'DENAUA-1022 - Participante Start crea el traceId común y lo añade a la cabeceras del LRA', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (57, 'DENAUA-1018 - Test unitario RequestService', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (58, 'DENAUA-1019 - Fase II - Tests unitarios - Inclusión configuración reintentos y dlt en kafka request', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (59, 'DENAUA-989 - Añadir java_opts custom por parte del proyecto al deployment', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (60, 'DENAUA-987 - Añadir propiedad en RestClient para configurar tamaño maximo payload', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (61, 'DENAUA-992 - Analisis error en generación de Swagger a partir de un OpenAPI yml', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (62, 'DENAUA-1021 - Fase II - Implementación Long Running Kafka', 3);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (63, 'DENAUA-1055 - [Testing] Cobertura, diseños de casos en ALM y Pruebas de operaciones en caché con MongoDb', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (64, 'DENAUA-1056 - [ALM] Revisión de la Poc Cache MongoDb para un correcto funcionamiento', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (65, 'DENAUA-950 - Análisis reenganche de request-reply cuando Kafka cae', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (66, 'DENAUA-1002 - Fase I - Implementación observabilidad LRA coordinator: Logs y Trazas agregados', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (67, 'DENAUA-980 - Subir versión de Spring Boot a la 3.3.2', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (68, 'DENAUA-1028 - Análisis para la posible implementación de un Starter SOAP', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (69, 'DENAUA-1047 - [Testing] Pruebas RI S3', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (70, 'DENAUA-943 - [Testing Automatización] Automatizar casos de Resiliencia', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (71, 'DENAUA-1046 - Obtención credenciales de secreto para llamar curl desde NauaCli', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (72, 'DENAUA-1041 - Pruebas nueva versión de FW DevOps y Chart de java', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (73, 'DENAUA-1035 - Realizar una RI de un consumidor Kafka de larga duración para probar el componente LongRunningConsumer', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (74, 'DENAUA-1043 - Creación/modificación gissWebApiClient llamada ApiConnect + ApplicationId', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (75, 'DENAUA-1038 - Crear constructor con todos los campos para clase GissErrorResponse', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (76, 'DENAUA-1071 - Añadir validaciones en operaciones S3', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (77, 'DENAUA-1053 - Activar trazas en Starter S3', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (78, 'DENAUA-1052 - Añadir opciones de filtrado en operación listObjects de starter s3', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (79, 'DENAUA-1051 - Añadir configuración de reintentos en clientes S3', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (80, 'DENAUA-1050 - Añadir nueva propiedad para endpoints adicionales securizados', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (81, 'DENAUA-1064 - [ALM] Corrección de defecto en cache Mongodb (tarea DENAUA-1036)', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (82, 'DENAUA-1058 - [Testing Automatización] Automatizar casos de la Gestión de Errores en Batch', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (83, 'DENAUA-1065 - [Soporte] Incluir centro de desarrollo UP', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (84, 'DENAUA-1066 - Ampliación funcionalidad RI Kafka Producer para envío evento a Consumer Long Running', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (85, 'DENAUA-1002 - Fase I - Implementación observabilidad LRA coordinator: Logs y Trazas agregados', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (86, 'DENAUA-1074 - Actualización de RIs a versión NAUA con Spring Boot 3.3.2', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (87, 'DENAUA-1050 - Añadir nueva propiedad para endpoints adicionales securizados', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (88, 'DENAUA-1056 - [ALM] Fase II: Revisión de la Poc Cache MongoDb para un correcto funcionamiento 1056', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (89, 'DENAUA-1068 - Corregir configuración Swagger para URL generada del servidor', 4);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (90, 'DENAUA-1070 - Creación API Mock carga inicial para NAUF según contrato acordado', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (91, 'DENAUA-1098 - Análisis de refactor en filtros JPA para valores múltiples', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (92, 'DENAUA-1108 - Pruebas configuración de reintentos en clientes S3', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (93, 'DENAUA-1096 - Añadir validaciones de extensión en clientes s3', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (94, 'DENAUA-1099 - Análisis de refactor en filtros MongoDB para valores múltiples', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (95, 'DENAUA-1107 - Testing Fase II-Pruebas RI S3', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (96, 'DENAUA-1070 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (97, 'DENAUA-1098 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (98, 'DENAUA-1089 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (99, 'DENAUA-1085 - Implementar en fw de devops lanzamiento chart LRA en base a flag en el values', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (100, 'DENAUA-1039 - Análisis refactor clase AuditableEntity de jpa y AuditableDocumentEntity de Mongo ', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (101, 'DENAUA-1082 - Actualización Version Java a la 21 con la ayuda de scripts', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (102, 'DENAUA-1048 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (103, 'DENAUA-897 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (104, 'DENAUA-1128 - Observabilidad SAGA, validar el correcto funcionamiento de las Trazas emitidas por la Observabilidad de la Saga', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (105, 'DENAUA-1109 - Compatibilidad versión de Spring Boot 3.3.2 y MongoDB', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (106, 'DENAUA-1102 - Ejecución manual de los test no automatizados', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (107, 'DENAUA-1100 - Pruebas Automaticas Framework NAUA', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (108, 'DENAUA-1084 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (109, 'DENAUA-1129 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (110, 'DENAUA-1078 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (111, 'DENAUA-1080 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (112, 'DENAUA-1049 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (113, 'DENAUA-1135 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (114, 'DENAUA-1101 - Refactorización de la clase WService ', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (115, 'DENAUA-1095 - LKR LongRunning consumer', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (116, 'DENAUA-1110 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (117, 'DENAUA-1131 - Pruebas RI Kafka Rquest/Replay', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (118, 'DENAUA-1141 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (119, 'DENAUA-1142 - nan', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (120, 'DENAUA-1145 - Añadir la cabecera X-GISS-REPRESENTATION al filtro que traspasa las cabeceras a los restclient ', 5);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (121, 'DENAUA-1204 - Eliminacion de contraseñas guardadas en NauaCli', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (122, 'DENAUA-1161 - Corrección defecto en RI multipledb', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (123, 'DENAUA-1060 - Mejoras de algunos metodos de NauaCli', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (124, 'DENAUA-1150 - Análisis + Poc viabilidad de starter JPA pasra permitir filtrado múltiple OR', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (125, 'DENAUA-735 - Análisis funcionalidad incluir recuento total de elementos en las colecciones en el framework', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (126, 'DENAUA-1149 - Implementación de filtrado de múltiples valores en starter Mongo', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (127, 'DENAUA-1206 - Prueba de RI Avo con nueva versión de Event Streams en integración', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (128, 'DENAUA-1045 - Consola Batch (Spring Cloud Data Flow): Creación y seguimiento issue comunidad Spring Batch5', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (129, 'DENAUA-1148 - Implementación de filtrado de múltiples valores en starter JPA', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (130, 'DENAUA-1033 - Analizar resultado del análisis  de sostenibilidad realizado por el equipo de observabilidad y aplicar corrección', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (131, 'DENAUA-1147 - Análisis métricas batch', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (132, 'DENAUA-1124 - Cambio en metodo checkversion seteo dinamico ruta Nauacli', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (133, 'DENAUA-1011 - Análisis arquitectura para la implementación del endpoint InitialLoading para proyectos Front', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (134, 'DENAUA-1137 - Modificación FW DEVOPS para adaptación del lanzamiento del chart Kafka a nuevos clusters en la nube (nuevo parámetro Cluster ID)', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (135, 'DENAUA-1048 - Analizar viabilidad de parar el webserver cuando finalice un job batch', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (136, 'DENAUA-828 - Análisis lanzamiento de job desde control-m y kafka', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (137, 'DENAUA-1207 - [Testing] Validar la funcionalidad de la ri ot_nauawcli_ri-web-client.', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (138, 'DENAUA-1188 - [Testing] Revisión casos, rediseño y pruebas por el cambio en la RI Cache Mongo ', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (139, 'DENAUA-1138 - [Testing] Pruebas de la RI ot_nauamult_ri_multipledb', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (140, 'DENAUA-1201 - [Testing] Ri Security 3', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (141, 'DENAUA-1190 - nan', 6);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (142, 'DENAUA-1211 - Análisis del uso de Chaos Monkey como herramienta de Testing para la mejora de las pruebas de Resilencia', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (143, 'DENAUA-915 - Incorporar Avro en el request_replay entre los servicos ot_apnarsql_request-service-layered y ot_apnarsql_reply-service-layered', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (144, 'DENAUA-1164 - [Testing] Fase II - Validar la funcionalidad de la ri ot_nauasec2_ri-security2 (ejecución pruebas)', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (145, 'DENAUA-1236 - [Testing] Validar la funcionalidad de la ri ot_nauasec3_ri-security3 - Fase II: Pruebas', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (146, 'DENAUA-1239 - Analizar resultado del análisis de sostenibilidad realizado por el equipo de Observabilidad y aplicar corrección - Fase II: Pruebas Observabilidad', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (147, 'DENAUA-1259 - Modificación FW DEVOPS para adaptación del lanzamiento del chart Kafka a nuevos clusters en la nube (nuevo parámetro Cluster ID) - Fase II: Pruebas', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (148, 'DENAUA-1237 - SOPORTE: Analizar el componente LongRunningConsumerService que no detiene el consumo, por PASS en Pensiones - Fase II: Pruebas Pensiones', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (149, 'DENAUA-1260 - Soporte creacion pipeline despliegue Kafka Connect INT', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (150, 'DENAUA-865 - Creación chart para desplegar aplicación batch como Cronjob y pruebas', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (151, 'DENAUA-1329 - Actualizar Framework DevOps para lanzar chart cronjob', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (152, 'DENAUA-1088 - Lanzar un job desde LRAAsynchronous Batch Launcher', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (153, 'DENAUA-1238 - Diagnóstico de errores en comandos lanzados desde chart Kafka en AWS', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (154, 'DENAUA-1205 - Inclusión de label con tallaje utilizado en el microservicio en chart java', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (155, 'DENAUA-1223 - Adición de la información mostrada en los labels como variables de entorno en chart Java', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (156, 'DENAUA-1224 - Mostrar en logs las variables de entorno que contienen la información de los labels', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (157, 'DENAUA-1175 - Implementación Starter MQZ - Fase I', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (158, 'DENAUA-1265 - Añadir adaptador Rest al microservicio 'certification' de APNA', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (159, 'DENAUA-1156 - Incluir nuevas métricas arenas (1/3) Nueva imagen añadiendo JavaPmapInspector', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (160, 'DENAUA-1157 - Incluir nuevas métricas arenas (2/3) - Crear script', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (161, 'DENAUA-1158 - Incluir nuevas métricas arenas (3/3) - Configurar tarea @Scheduled en framework', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (162, 'DENAUA-1162 - Aplicación nueva versión chart Java en RIs y probar las Ris', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (163, 'DENAUA-1212 - Creación de RI BFF', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (164, 'DENAUA-1213 - Estudio de clases, dependencias y propiedades comunes a los BFF para posterior inclusión en NAUA-Generator', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (165, 'DENAUA-1220 - Pruebas de ingesta de métricas de microservicio NAUA en DynaTrace', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (166, 'DENAUA-1209 - Filtrado de campos fecha en Jpa', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (167, 'DENAUA-1246 - Creación de un microservicios NAUA de pruebas para DevOps', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (168, 'DENAUA-1216 - Analizar funcionalidad de incorporarar', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (169, 'DENAUA-1187 - [Testing Automatización] Componente que gestiona Cache Mongo (II)', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (170, 'DENAUA-1242 - [Testing Automatización] Componente que gestiona MQSeries', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (171, 'DENAUA-1247 - [Testing Automatización] Componente que gestiona Multipledb', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (172, 'DENAUA-1254 - [Testing Automatización] Componente que gestiona WebClient', 7);
INSERT INTO tarea (id, descripcion, sprint_id) VALUES (173, 'DENAUA-1258 - [Testing] Validar la funcionalidad de la ri ot_nauawscl_ri-wsclient', 7);
