INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-13 - [VRSO-ANALISIS] Análisis de viabilidad de las mejoras propuestas por el equipo de VRSO', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-38 - [INT. CONF. MANAGER] Análisis de la información a migrar a Config Manager', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-19 - [VRSO] Disponibilizar como variable de entorno la versión generada de la aplicación', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-40 - [VRSO] Ejecución de aplicación VRSO con estaticos ya creados', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-39 - [VRSO] Creación de estaticos VRSO', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-28 - [Jenkins multitenant][ANALISIS] Levantar una instancia de jenkins en el namespace que nos ha facilitado Producción y sistemas y comprobar que está totalmente aprovisionado', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-29 - [Jenkins multitenant][INVESTIGACIÓN] Investigar como configurar automáticamente el cloud de los agentes en Jenkins', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-30 - [Jenkins multitenant][INVESTIGACIÓN] Investigar como configurar automaticamente los Plugins en Jenkins', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-31 - [Jenkins multitenant][INVESTIGACIÓN] Investigar como configurar automaticamente la Creación de Roles en Jenkins', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-8 - [FW MODULAR-API MANAGER] Creación de stages para gestión de APIs', 1);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-45 - [Jenkins multitenant] Completar la configuración del jenkins de producción y sistemas', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-44 - [VRSO-ANALISIS] Revisión de viabilidad del documento de mejoras de VRSO', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-46 - Análisis funcional del API REST de gestión de los jenkins. Primera versión', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-47 - [INT. CONF. MANAGER] Análisis de la información a migrar a Config Manager (Parte II)', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-10 - [FW Modular-API MANAGER] Crear ConfigAdapter para la gestión de apis', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-6 - [FW Modular-API MANAGER] Crear interfaz ITool para apic', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-7 - [FW Modular-API MANAGER] Implementar la interfaz ITool para apic', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-33 - [Jenkins multitenant][IMPLEMENTACIÓN] Implementar la configuración automática del cloud de los agentes en Jenkins', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-34 - [Jenkins multitenant][IMPLEMENTACIÓN] Implementar la configuración automática de los Plugins en Jenkins', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-35 - [Jenkins multitenant][IMPLEMENTACIÓN] Implementar la configuración automática de la Creación de Roles en Jenkins', 2);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-57 - [INT. CONF. MANAGER] Análisis de la información a migrar a Config Manager (Parte III)', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-53 - [Entornos postproductivos] Toma de requisitos para despliegues en Openshift', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-56 - [José María] Análisis funcional del API REST de gestión de los jenkins. Segunda versión', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-48 - [VRSO] Generación de pantallas para el análisis en Kiuwan', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-32 - [Jenkins multitenant][INVESTIGACIÓN] Investigar como configurar automaticamente los custom tools en Jenkins', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-51 - [Jenkins multitenant] Instalar plugins con versión definida', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-41 - [FW Modular-API MANAGER] Implementar list de catálogos en la interfaz ITool para apic', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-42 - [FW Modular-API MANAGER] Implementar list de versiones de productos en la interfaz ITool para apic', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-59 - [Jenkins multitenant] Probar flujo completo de aplicaciones con despliegue XL y HELM', 3);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-72 - Análisis de la información a migrar a Config Manager (Parte IV)', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-73 - Análisis funcional del API REST de gestión de los jenkins. Tercera versión', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-75 - [Despliegue entornos postproductivos-Openshift] Alternativas para dar solución a los requisitos solicitados por PYS', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-71 - [VRSO] Crear documento indicando los cambios realizados', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-69 - [Jenkins multitenant] Dar de alta a los usuarios de equipo DevOps para administrar Jenkins de producción y sistemas', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-70 - [Jenkins multitenant] Dar de alta a los usuarios de equipo producción y sistemas para administrar Jenkins de producción y sistemas', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-60 - [Jenkins multitenant] Configuración entorno de desarrollo para framework naua', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-74 - [Jenkins multitenant] Formación sobre endpoints securizados en framework naua', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-62 - [Jenkins multitenant] Investigar como obtener el estado de un pod a partir de una etiqueta', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-43 - [FW Modular-API MANAGER] Modificar el ConfigAdapter para que devuelva el comando correcto (publish, replace o supersede) según la configuración del proyecto', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-78 - [VRSO] Análisis y creación de la imagen de agente con python 3.11 con los paquetes necesarios para el funcionamiento de VRSO', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-63 - [Kevin][FW Modular- API MANAGER] Añadir en base de datos las propiedades de servidor de api management', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-77 - [VRSO] Generación de pantallas para el análisis en Kiuwan, gestión de errores en kiuwan.sh', 4);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-81 - [Jenkins multitenant] Adaptar los scripts de ot_fdarfrwl_task', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-92 - [Jenkins Multitenant] InvestigarVerificar el impacto del Configuration as Code sobre la configuración existente.', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-82 - [Jenkins multitenant] Repositorio gitlab para la configuración de los nuevos jenkins', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-84 - [Entorno postProductivo FOR] Generar métodos en FW actual para descargar plantillas de P&S desde la URL definida en la BBDD.', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-85 - [[Entorno postProductivo FOR]] Generar métodos en FW actual para enviar correo a P&S a través del Pass.', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-89 - [Entorno postProductivo FOR] Realizar validaciones en el entorno post-productivo FOR.', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-91 - [Entorno postProductivo FOR] Crear métodos para la creación de la pipe de FOR en el entorno de formación.', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-90 - [Entorno postProductivo FOR] Investigar y verificar el FW para confirmar si la infraestructura permite actualmente el entorno FOR y crea el artefacto y recursos correspondientes para este entorno', 5);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-101 - [Entorno postproductivo FOR] Corregir cálculo de ruta de despliegue manual de job de Jenkins entorno de Formación en correo de notificación', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-103 - [Entorno postproductivo] Desplegar correctamente una aplicación en entorno de formación y corregir los distintos errores que vayan surgiendo', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-83 - [Jenkins multitenant] Crear en el proyecto ot_fdarback_main los endpoints para gestión de jenkins multitenant', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-96 - [Config manager] Validación de jerarquías con config manager', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-64 - [FW Modular-API MANAGER] Repositorio gitlab para planes y políticas de seguridad', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-79 - [FW Modular-API MANAGER] Aplicar configuración de plan definida por el proyecto', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-80 - [FW Modular-API MANAGER] Aplicar configuración de política de seguridad definida por el proyecto', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-105 - Realización de documentación de entregables', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-95 - [Jenkins multitenant] Probar y terminar configuración del nuevo jenkins para el centro de desarrollo OT', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-94 - [Entorno postproductivo FOR] Documentación de como realizar el despliegue en formación via pipe', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-65 - [FW Modular-API MANAGER] Subir el  artefacto zip para despliegue a Nexus', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-67 - [FW Modular-API MANAGER] Usar artefacto zip de nexus para despliegue', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-87 - [Jenkins multitenant] Login al cluster de openshift', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-102 - [FW Modular-API MANAGER] Modificar es.giss.framework.api_management.ApicTool#listProductVersions para obtener name y url', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-93 - [Jenkins multitenant] Aplicar los parámetros al template de jenkins y crear jenkins', 6);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-100 - [FW Modular-API MANAGER] Modificar el ConfigAdapter para que devuelva el comando correcto (publish, replace o supersede) según la configuración del proyecto en nuevo fichero values.yaml [REVISAR]', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-108 - [Jenkins Multitenant] Crear nueva instancia de Jenkins para el centro de desarrollo TG', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-122 - [Jenkins multitenant] Integrar la creación de jenkins con el endpoint de instalacción de Jenkins', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-109 - [Jenkins multitenant] Crear cliente git para clonar repositorio', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-113 - [Config manager] Crear script que extraiga información de los repositorios generando un JSON', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-110 - [Jenkins multitenant] Creación de roles partiendo de la información existente en el repositorio gitlab', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-114 - [Config manager] Crear script que extraiga información de los repositorios generando un JSON por entorno', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-111 - [Jenkins multitenant] Instalación de plugins partiendo de la información existente en el repositorio gitlab', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-112 - [Jenkins multitenant] Configuración de shared libraries partiendo de la información existente en el repositorio gitlab', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-115 - [Jenkins multitenant] Instalación de custom tools partiendo de la información existente en el repositorio gitlab', 7);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEABDV-117 - [Jenkins multitenant] Probar y terminar configuración del nuevo jenkins para el centro de desarrollo TG', 7);
