INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario, Félix', 1, 1, 1, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 1, 2, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel, Pablo', 1, 1, 3, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel, Pablo', 1, 1, 4, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel, Pablo', 1, 1, 5, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin, Julian', 1, 1, 6, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin, Julian', 1, 1, 7, 'Usado a modo particular, sin promtp de GISS. Resumir texto y describir. Además de pedir ejemplos de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel, Kevin', 1, 1, 8, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo, Julián', 1, 1, 9, 'Usado a modo particular. Solicitado ejemplos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose Maria, Carlos', 1, 1, 10, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin, Julian, Pablo y Alejandro', 1, 2, 11, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario, Félix', 1, 2, 12, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('José María', 1, 2, 13, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 2, 14, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos, Manuel', 1, 2, 15, 'Usado a modo particular, sin promtp de GISS');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos, Manuel', 1, 2, 16, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos, Manuel', 1, 2, 17, 'Usado a modo particular, sin promtp de GISS');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Julián, Pablo', 1, 2, 18, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin, Alejandro', 1, 2, 19, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 2, 20, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 3, 21, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 3, 22, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose María', 1, 3, 23, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 3, 24, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Julián', 1, 3, 25, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 3, 26, 'Utilizado para la compresión y desarrollo con la API de jenkins. ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 3, 27, 'Usado a modo particular y con promtp de GISS.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 1, 3, 28, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 1, 3, 29, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 4, 30, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose María', 1, 4, 31, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 4, 32, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 4, 33, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 4, 34, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 4, 35, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin, Jose María y Manuel', 1, 4, 36, 'Ha sido necesario reescribir la historia casi desde cero.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 1, 4, 37, 'Sesión de formación. No aplica IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 4, 38, 'Ha sido necesario reescribir la historia casi desde cero.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos y Alejandro', 1, 4, 39, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo y Manuel', 1, 4, 40, 'No ha sido nacesario en esta historia');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 4, 41, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 4, 42, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 5, 43, 'No ha sido nacesario en esta historia');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 5, 44, 'Ha sido utilizada para generar la documentación del proceso');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos y Alejandro', 1, 5, 45, 'No ha sido nacesario en esta historia');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 5, 46, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo y Carlos', 1, 5, 47, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose María', 1, 5, 48, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin y Manuel', 1, 5, 49, 'IA utilizada principalmente para comprender codigo y refactorizar');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 5, 50, 'No utilizada IA por ser una historia muy sencilla');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 6, 51, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 6, 52, 'No ha sido nacesario en esta historia');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose María, Alvaro', 1, 6, 53, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 6, 54, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 1, 6, 55, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 1, 6, 56, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pablo', 1, 6, 57, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario, Félix', 1, 6, 58, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 6, 59, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 1, 6, 60, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 6, 61, 'IA utilizada principalmente para comprender codigo y refactorizar');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', 1, 6, 62, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 6, 63, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Manuel', 1, 6, 64, 'IA utilizada para comprender código');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Kevin', 1, 6, 65, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 66, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 67, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 68, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 69, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 70, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 71, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 72, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 73, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 74, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 75, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 1, 7, 76, 'nan');
