INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-1 - Instalación local y Análisis IDP ExperientalLab', 8);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-2 - Análisis foto global con ONBO y ConfigManager', 8);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-3 - Definición y priorización de las personalizaciones a realizar en la plataforma', 8);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-5 - Definición de escenarios y casos de uso a incluir en el proyecto', 8);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-10 - Definición de escenarios y casos de uso a incluir en el proyecto (detalle)', 9);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-14 - Analisis para la creación del template de carga de aplicaciones y uso de ONBO', 9);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-15 - Fase I:Analisis configuración y customización componente core SW Catalog', 9);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-16 - Fase I: Analisis configuración y customización componente core SW Search', 9);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-4 - Identificar primeras 5 aplicaciones a cargar en la plataforma', 9);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-6 - Prueba ejecución IDP ExperientalLab', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-17 - Fase I: Analisis configuración y customización componente core SW TechDocs', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-19 - Definición y priorización de las personalizaciones a realizar en la plataforma (detalle))', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-18 - Analisis de la funcionalidad de carga de aplicaciones existentes', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-25 - Fase 2: Analisis configuración y customización componente core SW Catalog', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-26 - Fase 2: Analisis configuración y customización componente core SW Search', 10);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-27 - Definición del modelo de entidades para realizar la carga de aplicaciones', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-34 - Configuración componente CORE SW catálogo', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-35 - Configuración componente CORE SW TechDocs', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-36 - Configuración componente CORE SW Search', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-28 - Carga de aplicación 1', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-29 - Carga de aplicación 2', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-30 - Carga de aplicación 3', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-31 - Carga de aplicación 4', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-32 - Carga de aplicación 5', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-37 - Análisis de configuración RBAC', 11);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-21 - Análisis configuración Plugin Gitlab', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-22 - Análisis configuración Plugin Nexus', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-20 - Análisis configuración Plugin Jira', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-24 - Análisis configuración Plugin ApiDocs', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-38 - Aplicar personalizaciones', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-46 - Concepto alto nivel carga inicial de aplicaciones y elementos promocionables', 12);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-39 - Autenticación de Backstage', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-47 - Adaptación a GISS Plugin Gitlab', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-53 - Configuración Plugin Jira', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-64 - Análisis requerimientos nuevo plugin Kiuwan', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-54 - Renderizar documentación en formato PlantUML', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-62 - Análisis e instalación de plugin Dynatrace', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-51 - Configuración plugin Dynatrace', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-55 - Análisis e instalación de plugin Retina', 13);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-65 - Autorización: Obtener roles de Silcon', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-66 - Autorización: Asignar Rol al usuario', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-73 - Configurar plugin kiuwan', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-69 - Configurar Plugin Jira en Openshift', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-76 - Configurar y Adaptar a GISS plugin Retina', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-70 - Adaptar Plugin Jira para GISS', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-74 - Carga inicial y estándar de 5 aplicaciones nuevas identificadas por GISS', 14);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DESTAG-75 - Configurar y Adaptar a GISS plugin Dynatrace', 14);
