INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 132, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 133, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 134, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 137, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 1, 4, 138, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 8, 4, 138, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 139, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 140, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 141, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 141, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 142, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 143, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 144, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 146, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 147, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 148, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 148, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 150, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 151, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 153, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (7, 0.3, 0.45, 154, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (6, 0.2, 0.25, 155, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (6, 1, 2, 155, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (9, 0.25, 0.5, 156, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (2, 5, 3, 156, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 157, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (5, 0, 0, 157, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 157, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 159, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (7, 2, 4, 159, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (8, 1, 2, 163, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (7, 6, 8, 169, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 174, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 175, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (8, 1, 2, 175, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 180, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 181, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 182, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, estimacion_id, prompt_id) VALUES (' ', 0, 0, 183, 21);
