INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 15, 124, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 15, 125, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 15, 126, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge, Alejandro, Sergio', 3, 15, 127, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 15, 128, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 15, 129, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 15, 130, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 15, 131, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 15, 132, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 16, 133, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 16, 134, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 16, 135, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 16, 136, 'La IA no me generó respuestas eficaces en los test');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 16, 137, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 16, 138, 'No ha sido necesario el uso de IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 16, 139, 'Utilizada IA para generar patrón con expresión regular. Respuesta satisfactoria por parte de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 16, 140, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 16, 141, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 16, 142, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 16, 139, 'La IA me generó respuestas eficaces');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 17, 143, 'La IA me generó correctamente el patrón para aplicarlo.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 17, 144, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 17, 145, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 17, 146, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 17, 147, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 17, 148, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 18, 149, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 18, 150, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 3, 18, 151, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 18, 152, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 18, 153, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 18, 154, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis', 3, 18, 151, 'El prompt se queda atascado si el open-api es extenso. ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio, Oscar', 3, 18, 155, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 3, 19, 156, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto, Alejandro', 3, 19, 157, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 3, 19, 158, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 19, 159, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Oscar', 3, 19, 160, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto, Alejandro', 3, 20, 161, 'utilizada IA para comporbar si GIT tenía métodos para setear una rama como default');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro, Alberto, Oscar', 3, 20, 162, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro, Alberto', 3, 20, 163, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 20, 164, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 20, 165, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Oscar', 3, 20, 166, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Luis, Alberto, Alejandro', 3, 21, 167, 'Se usó IA para la generación de un trigger de BD');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 21, 168, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 21, 169, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 3, 21, 170, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio, Oscar', 3, 21, 171, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 22, 172, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro, Alberto', 3, 22, 173, 'Usada IA para generar query con todos los campos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 22, 174, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Todos', 3, 22, 175, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jorge', 3, 22, 176, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 3, 22, 177, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 3, 22, 178, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Oscar', 3, 22, 179, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Sergio', 3, 22, 180, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 3, 22, 181, ' ');
