INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-163 - Versionado: Análisis y diseño', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-165 - Config Manager: Análisis Refactorización del front actual', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-164 - Versionado: Añadir columna "version" al modelo de datos', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-167 - Versionado: Definición del API REST (front-back)', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-168 - Versionado: Ms_commander: Añadir versión en evento', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-182 - Reunión con devops para recopilar requisitos', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-166 - Versionado: Frontend. Agregar campo "versión" en alta/modificación de propiedad', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-177 - Versionado: Frontend. Agregar campo "versión" en alta/modificación de credenciales', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-174 - Versionado: Frontend. Agregar campo "versión" a listado de propiedades y credenciales', 15);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-173 - ONBO. Actualización de versión del API de MACA', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-183 - Recopilar requisitos con devops para integrar en config manager', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-169 - Versionado: Ms_hierarchy: Añadir versión en evento', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-170 - Versionado: Ms_Credential: Añadir versión en evento', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-171 - Versionado: Definición del API REST (initContainer - runtime)', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-185 - Actualizar valor por defecto de version en Property y Credential', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-186 - BACK: Aplicar patrón al valor del campo version', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-178 - Versionado: Frontend. Agregar campo "versión" a listado de credenciales', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-175 - Versionado: Frontend. Agregar campo "versión" en alta de sobrescritura', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-176 - Versionado: Frontend. Borrado de una propiedad o credencial', 16);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-196 - INT back-front: Aplicar patrón al valor del campo version', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-189 - Versionado. Borrado automático de versión inicial', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-187 - RUNTIME: Aplicar lógica de version a GetProperty', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-188 - RUNTIME: Aplicar lógica de version a GetCredential', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-190 - As-A-Volume: Análisis y diseño', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-193 - As-A-Volume: [Front] Implementación de listado de volúmenes', 17);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-200 - ms_credential: Actualizar funcionalidades en base a UK', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-184 - Versionado: Promoción a CER de la funcionalidad de versionado', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-205 - As-A-Volume: API Rest. Definición endpoints para volumen', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-191 - As-A-Volume: Creación del Modelo de Datos', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-207 - As-A-Volume: Back. Modificación de ms_commander', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-206 - As-A-Volume: Back. Creación microservicio NAUA asavolume', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-204 - As-A-Volume: Front. Creación y edición de un volumen', 18);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-212 - As-A-Volume: Pruebas INT front - back', 19);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-219 - As-A-Volume: Implementar lógica en Runtime', 19);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-214 - As-A-Volume: Promoción a CER', 19);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-221 - Versionado: FrontEnd. Rol DBA no puede dar de alta propiedades.', 19);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-226 - [ONBO Prod] Campo email editable', 19);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-228 - [Onbo Prod] Scaffolding/GitLab: tras finalizar el proceso, la rama develop debe marcarse como Default.', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-232 - No cargar los datos de mongo si una aplicación está finalizada', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-199 - Información del combo de aplicaciones (CAPP + descripción larga)', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-229 - Corrección de bugs de criticidad C1', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-230 - Corrección de bugs de criticidad C2', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-238 - Front: Refactorización de CM', 20);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-75 - Versionado: Back: Añadir característica de latest a Propiedad', 21);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-234 - Envio de email usando un template', 21);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-248 - Versionado: Back: Gestión de overwritable en sobreescritura', 21);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-224 - Versionado: Modificar API REST front back para incorporar "latest" en el objeto "Propiedad"', 21);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-225 - Versionado: Front: Implementación de latest', 21);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-172 - ms_runtime: Implementación de la lógica para"latest" en "Propiedad"', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-249 - [DevOps] Migración propiedades Jenkinsfile', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-268 - Desplegar en CER, PRE, PRO nueva funcionalidad de ONBO', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-269 - Soporte a QA/PRE Config Manager (Latest + Volúmenes) (Preexplotacion):', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-270 - Subir el chart de DevOps y de NAUA en todos los micros de ONBO', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-271 - Subir versión del chart de DevOps y de NAUA en todos los micros de CM', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-253 - [DevOps] Migración propiedades TestingJenkinsFile', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-257 - Front Campos para para alta en KIUWAN', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-259 - Campos para alta de repositorio de Liquibase', 22);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXGC-262 - Campos para alta de repositorio de testing', 22);
