INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 1, 4, 1, 138, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 8, 4, 1, 138, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 1, 141, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 1, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 1, 145, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (' ', 1, 2, 1, 148, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (7, 0.3, 0.45, 1, 154, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (6, 0.2, 0.25, 1, 155, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (6, 1, 2, 1, 155, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (9, 0.25, 0.5, 1, 156, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (5, 0, 0, 1, 157, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (7, 2, 4, 1, 159, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (8, 1, 2, 1, 163, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (7, 6, 8, 1, 169, 21);
INSERT INTO medicion_por_prompt (calidad_salida_ia, estimacion_con_ia, estimacion_sin_ia, usada_ia, estimacion_id, prompt_id) VALUES (8, 1, 2, 1, 175, 21);
