INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1469 - [Framework DevOps Modular] Piloto Integración del Proyecto APNA Naua- Pipe construccion, kiuwan , despliegue , registro en backend.', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1461 - Validaciones previas a los despliegues en PRO fase I', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1465 - [Framework] Notificar a Calidad de los despliegues en CER y PRE', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1467 - [Framework] Despliegue obligatorio en PRE elementos promocionables que no sean librería', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1451 - Adaptación chart de dvo_helm-charts_ms-java (prosa/java) para arquitectura prosa', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1452 - Sufijo a release de aplicaciones de arquitectura prosa', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1453 - Nuevo campo en values de aplicaciones de arquitectura prosa', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1430 - [Framework Modular] Fase POST- Envio de correos pipes/emails.xml', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1431 - [Framework Modular] Fase POST- Envio de correos pipes/emails_nexus.xml', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1417 - [Framework Modular]ConfigAdapter para el backend, consulta release', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1468 - [ANALISIS] Artefactos comprimidos para Portales.', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('TICKET PASS - Crear SCRIPT para Artefactos de Nexus', 23);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1480 - [Framework DevOps Modular] Piloto: Corrección de errores y mejoras en las pipelines del framework modular ', 24);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1478 - [Framework DevOps Modular] Implementar catalogo de validaciones ', 24);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1477 - [Framework DevOps Modular] Crear repositorio para guardar las validaciones de DevOps para el modulo de politica', 24);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1429 - [BACKEND] Cambiar el registro del proyecto para que si ya existe, actualice también la URL ', 24);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1472 - [Framework] Fallar la pipeline cuando CD=true y no hay un valor correcto en TOOLS_DEPLOY', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1476 - [PORTALES LIFERAY] Eliminar el doble comprimido al generar el artefacto en Nexus', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1482 - Creación de agente único para Framework Modular', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1471 - Configurar el Jenkins de gint-co-dvo para incluir Framework Modular', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1386 - [Framework DevOps Modular] [Módulo Políticas] Catálogo nuevo validaciones en función del entorno y filtrado de validaciones por etiquetas.', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1485 - [Framewor DevOps Modular] Crear y configurar Credencial para Gitlab Api Rest', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1481 - [Framework DevOps Modular] [Módulo Core] Crear nuevo Custom Tools para GraalVM', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1486 - [Framework Modular] [Módulo HELM] Corregir coordenadas de artefactos en repositorios Helm Deploy', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1475 - [Framework DevOps Modular] [Módulo Release] Crear el modelo de datos para ReleaseDescriptor', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1484 - [Framework DevOps Modular] [Módulo Notificaciones] Refactorizar codigo de envio de emails y separacion de funcionalidad', 25);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1489 - Formacion de las bases del Framework Modular.', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1493 - [Framework] Establecer por defecto ciclo PRE si el endpoint de HARA devuelve error', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1473 - Generar version RC y pruebas (5.2.0-RC)', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1497 - Sacar versión V5.1.2 con pruebas mínimas de HOTFIX', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1490 - [Framework] Independizar el framework del repositorio de GitLab donde se encuentran los HELM CHARTS', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1495 - Soporte a equipo de ISAC para configuración de Framework Modular', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1487 - [Framework DevOps Modular] [Módulo Políticas] Catálogo nuevo validaciones en función del entorno', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1488 - [Framework DevOps Modular] [Módulo Políticas] Filtrado de validaciones por etiquetas', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1504 - Corregir test unitarios ', 26);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1514 - Soporte a equipo de ISAC para configuración de Framework Modular', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1498 - [PROSA] [APLICACIONES COMUNES] Pruebas a realizar para validar la ejecución de aplicaciones comunes', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1503 - Generar versión V5.2.0', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1515 - Validar con calidad el estado de la shared library de kiuwan de cara a la integracion con FRW Modular', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1439 - [Framework DevOps Modular] Crear ConfigAdapter para el backend que deje datos en el releaseDescriptor', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1432 - [Framework Modular] Fase POST- Envio de correos a delegados', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1456 - [Framework Modular] Crear política para validar la respuesta de HARA (formulario + test pre/post)', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1433 - [Framework Modular] Envío de correos de test PRE/POST para RELEASE', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1499 - [Framework DevOps Modular] Piloto Integración del Proyecto APNA Naua- INT y CER', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1510 - [Framework DevOps Modular] Comprobacion de UTF8 en ficheros de fuentes', 27);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1519 - Soporte a equipo de ISAC para configuración de Framework Modular-Sprint 45', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1516 - [Framework DevOps Modular] Piloto  Integración del Proyecto APNA Naua en gint-co-dvo', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1517 - [Framework modular] Resolver y completar etapas del pipeline de Framework modular detectados en el piloto', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1520 - [Framework DevOps Modular] Completar la información de los artefactos generados y moverlos a ReleaseDescriptor', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1523 - [Jenkins] - Análisis y diagnostico y de problemas de rendimiento del Jenkins de gpro-co-dvo', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1522 - [Framework Modular] Soporte e integración de la shared de calidad - Kiuwan', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1397 - [Framework Modular] Fase POST- Envio de correos por merge a master', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1501 - [Framework Modular] Pipe de MASTER creacion de Tag release', 28);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1540 - Framework DevOps Modular] Piloto Integración del Proyecto APNA Naua en gint-ps-dvo-Sprint 46', 29);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1536 - [Framework Modular] Configurar comando alternatives con java8 correctamente para Kiuwan', 29);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1542 - [Framework DevOps Modular] Soporte para resolver problemas con el despliegues de helm con el framework modular', 29);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1539 - Soporte a equipo de ISAC para configuración de Framework Modular-Sprint 46', 29);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1537 - [Framework Modular] Volcar al ReleaseDescriptor los detalles de los merge de GitLab para correos a PYS', 29);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEVOPS-1530 - [Framework DevOps Modular] Añadir validación para comprobar la existencia previa de un tag en el repositorio antes de PaseAProducción.', 29);
