INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 23, 182, 'Rocio y Alejandro: El piloto consiste en hacer pruebas, para las pruebas en sí no se ha utilizado');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 23, 183, ' ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 23, 184, 'Jaime: No se ha utilizado la IA ya que solo había que añadir nuevos destinatarios en los correos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 23, 185, 'Noemi: Se usó el prompt de historias de usuario V1. Los criterios de aceptación no salen en el forma');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 23, 186, 'La HDU ha sido creada por Félix. Aplica IA pero en este caso no se ha utilizado.Rocío:Se usó el prom');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 23, 187, 'La HDU ha sido creada por Félix. Aplica IA pero en este caso no se ha utilizado.Rocío:Se usó el prom');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 23, 188, 'La HDU ha sido creada por Félix. Aplica IA pero en este caso no se ha utilizado.Rocío:Se usó el prom');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 23, 189, 'Cristhian: No se ha utilizado IA al tratarse de la migración de un código cuyo funcionamiento ya con');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 23, 190, 'Cristhian: No se ha utilizado IA al tratarse de la migración de un código cuyo funcionamiento ya con');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 23, 191, 'Cristhian: No se ha utilizado IA al tratarse de la migración de un código cuyo funcionamiento ya con');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 23, 192, 'Juan: No se ha utilizado por ser una tarea de investigacion en el Framework antiguo');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jose María', 4, 23, 193, 'Jose María: Utilizado para desarrollar el inicio del script, corregir errores y mejorar el código. N');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 24, 194, 'Rocio y Alejandro: El piloto consiste en hacer pruebas, para las pruebas en sí no se ha utilizado. E');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 24, 195, 'Cristhian: La IA ha sido utilizada para ayudar en la creación de un fichero YAML, pero sin la utiliz');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 24, 196, 'Cristhian: La IA ha sido utilizada para refactorizar el código, ayudar en la creación de regex y cre');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 24, 197, 'Rocio: Para el despliegue del backend no se ha utilizado IA. Los cambios eran minimos y ya teníamos ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 25, 198, 'Alejandro: No se utilizaron los prompts de IA, ya que entendía el código del framework y el desarrol');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 25, 199, 'Juan: AL ser una correccion en el comportamiento del código solo se utilizo la IA para la HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 25, 200, 'Jaime: Se utiliza la IA para la configuración del Dockerfile y del buildconfig.yaml para la creación');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 25, 201, 'Cristhian: Configuración de Jenkins, no aplica IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 25, 202, 'Juan: la IA desvaria un poco respecto a la respuestas de regex, he tenido que verificar todas las re');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 4, 25, 203, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 25, 204, 'Alejandro: En esta tarea he usado bastante la IA, no así los prompts. El prompt de codigo me ha sido');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 25, 205, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 25, 206, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 25, 207, 'Cristhian: Se podría haber utilizado el prompt Code Refactor, pero la refactorización era muy sencil');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 26, 201, 'Cristhian: Configuración de Jenkins, no aplica IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 26, 208, 'Alejandro: Para la tercera formación, primera que imparto yo, me ha facilitado a la hora de entender');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 26, 209, 'Rocío: No aplica IA porque la tarea estaba muy bien explicada con anterioridad y el cambio estaba mu');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío y Juan', 4, 26, 210, 'Rocío y Juan: No aplica IA al ser lanzamiento de pruebas en jenkins para  comprobar el correcto func');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 26, 211, 'Rocio: No aplica IA, era sacar una nueva versión del fw después de haber realizado unas pruebas.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 26, 212, 'Rocío: Aplica IA para comprender el código fuente ya implementado y comprender donde tenia que reali');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 26, 204, 'Alejandro: La tarea consistia en generar una clase de configuracion de herramientas graalVM. He util');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 26, 213, 'Alejandro: La tarea consistia en dar soporte a una compañera de ISAC. Tenía errores al lanzar el fra');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 26, 214, 'Juan: continuacion del sprint anterior');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 26, 215, 'Cristhian: No aplica IA al ser un desarrollo sencillo y conocer previamente como debe realizarse.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 26, 216, 'Juan: No fue necesario el uso de la IA para la solucion de los tests unitarios ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 27, 217, 'Alejandro: La tarea consistia en dar soporte a una compañera de ISAC. Tenía errores al lanzar el fra');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 27, 218, 'Cristhian: La tarea consiste en comprobar que las aplicaciones se construyen correctamente, por lo q');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 27, 219, 'Juan: No aplica ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 27, 220, 'Alejandro: La tarea consistia en integrar Kiuwan con el FwModular coordinandonos entre los dos equip');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 27, 203, 'Cristhian: La tarea consiste en solicitar a Sistemas la creación de los diferentes recursos necesari');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 27, 221, 'Juan: Se ha utilizado para refactorizar codigo');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 27, 222, 'Jaime: La tarea consiste en ampliar el módulo de correos con una nueva plantilla de correo. No aplic');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 27, 223, 'Cristhian: Se utiliza IA para agilizar la creación de la validación.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 27, 224, 'Cristhian: La tarea consiste en ampliar el módulo de correos con una nueva plantilla de correo. No a');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 27, 225, 'Juan: No aplica ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 27, 226, 'Jaime: Se utiliza la IA para la refactorización del código. ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 28, 227, 'Ale: No aplica IA. La tarea se basa en darle soporte al equipo ISAC para que puedan lanzar su aplica');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 28, 228, 'Jaime: No aplica, son solamentes pruebas del piloto');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 28, 229, 'Jaime: No aplica');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 28, 230, 'Esta tarea se sacó del sprint por reducción de horas disponibles del equipo');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 28, 231, 'Ale: No aplican los prompts de IA. La tarea se basa en investigación sobre zonas de memoria. Se util');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro Rodriguez', 4, 28, 232, 'Ale: La tarea la realizó Cris, ya que la prioridad era Jenkins.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rocío', 4, 28, 233, 'Rocío: la parte de correos la había desarrollado mi compañero Alejandro por lo que me estuvo explica');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 28, 234, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Christian', 4, 29, 235, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Juan Jesús', 4, 29, 236, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Jaime Romero Caro', 4, 29, 230, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES (' ', 4, 29, 237, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 4, 29, 238, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 4, 29, 239, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 4, 29, 240, 'nan');
