INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdewrap_HU717  - Cambios de seguridad en wrappers', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdesopo_HU718 - Cambios de seguridad en servicios de soporte', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DECCLO-712 - Utilidades de servicios de soporte en librería CORE', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DECCLO-715 - Completar el perfilado de las historias asociadas a Note Alta y Consulta.', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdecoma_HU713 - Envío de SMS controlado desde la librería.', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdeangu_HU620 - Pantalla de consulta de Tratamientos en Maestros', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdeanpr_HU657 - Microservicio Procedimientos. Método para asociar tratamientos a procedimientos', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdeanpr_HU656 - Microservicio Procedimientos. Método para desasociar Procedimiento a Tratamiento', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdeanpr_HU710 - Microservicio Procedimientos. Obtener operaciones de un procedimiento.', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('nmdeanpr_HU708 - Microservicio Procedimiento. Método para borrar procedimiento', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DECCLO-726 - Refactorización de código en la aplicación de Gestión NMDE', 30);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('TMDE_HU_1970 - Investigación de configuraciones para la generación de logs sobre ClienteRTEA en MDE en WebMethods 10.15', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPP_1952 - [Firma sin certificado] XV25B00A permitir descarga nuevo justificante, xml y certificado de acuse', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPP_1961 - Entrega versión 01.49', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDIGA-2045 - NOTE: Incidencia Certificados empleado publico', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOTE_2041 - Entrega versión 08.12', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDIGA-2042 - NOTE: Soporte Notificaciones', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDIGA-2043 - REGISTRO: Soporte Registro', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDIGA-2044 - TMDE: Soporte TMDE', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOTE_2039 - Traspaso conocimientos.', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPP_2040 - Traspaso conocimientos.', 31);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMA_HU_1263 - Control de excepciones Kiuwan', 32);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMA_HU_1268 - Entrega 4.7.2', 32);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMA_HU_1225 - [Notificaciones Postales] - (1) Envío de notificación postal utilizando la operación "Notificación Envío Postal" de MDE (BBDD y Pantalla sin llamar a MDE)', 32);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMA_HU_1269 - [Notificaciones Postales] - (2) Envío de notificación postal utilizando la operación "Notificación Envío Postal" de MDE - (Envío a MDE)', 32);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMA_HU_1257 - Notificaciones especiales: sustituir texto en emails cortesías (NOMACORT)', 32);
