INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-142 - gRPC: añadir al framework NAUA la capacidad de añadir un gRPC client', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-147 - Publicar RI de cache-mongo en NAUA', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-153 - Generación de KPIs: Acceso BD vs Acceso Cache', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-156 - Análisis caso de uso Caching en PDCF', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-157 - Microservicio con driver dvm y dialectos Oracle o MySql', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-159 - Infinispan: Queries dinámicas, uso de ickle querys e índices', 33);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-162 - CU PDC: Implementación microservicio de infraestructura', 34);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-160 - Generación de KPIs: Acceso BD vs Acceso Cache (embebida)', 34);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-161 - Documento resultados KPIs completos Oracle vs Cache (Remota y Embebida)', 34);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-154 - Generación de KPIs: gRPC vs API REST', 34);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-168 - Análisis caso de uso Caching en PDCF', 34);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-148 - Publicar generator dvm bajo gissapisync', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-158 - Starter dvm: Actualización y publicación', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-173 - Estudio gRPC bidireccional', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-171 - CU PDC: Implementación microservicio genérico de infraestructura', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-174 - gRPC: Construir POC usando el modo bidireccional de gRPC', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-175 - Dialecto Adabas: Listado querys con error de sintaxis', 35);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-180 - CU PDC: Completar ms infraestructura', 36);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-181 - gRPC: Completar POC modo bidireccional de gRPC', 36);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-186 - CU PDC: Tabla Oracle. Log. Configuración ADD SUPLEMENTAL', 36);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-150 - gRPC: Generador de .proto', 36);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-188 - [Pipe Debezium] Capacitación en Helm y Charts para Pipeline Parametrizable para Debezium', 37);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-190 - [Pipe Debezium] Recopilar requisitos de uso del values.yaml', 37);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-182 - CU PDC: Incorporación ms de infraestructura a PDCF (INT)', 37);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-167 - gRPC: Subida de artefactos generados a NEXUS. Fase II Pipeline', 37);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-146 - gRPC: Generación de artefactos. Fase I pipeline', 37);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-189 - [Pipe Debezium] Análisis del API de Kubernetes para el Aprovisionamiento de Kafka Connect', 38);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-194 - CU PDC: Despliegue del microservicio CDC en entorno INT de PDCF', 38);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-200 - Análisis IA generativa para ICONA', 38);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-201 - gRPC: Comprobar Flujo de credenciales para comunicación entre server - client', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-196 - CU PDCF: Actualización de microservicio ms_consulta en PDCF', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-193 - [Pipe Debezium] [EV local] Despliegue de Kafka Connect mediante Helm', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-191 - [Debezium] Estudiar la observabilidad del conector. API kafka', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-197 - [Pipe Debezium] INT Despliegue de Kafka Connect mediante Helm', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-198 - [Debezium] POC en EV local. Observabilidad del conector', 39);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-206 - [gRPC] Starter gRPC no securizado a NAUA', 40);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-207 - [gRPC] Actualizar generador para uso del starter no securizado', 40);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-208 - gRPC: Actualización POC gRPC client', 40);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-209 - gRPC: Actualización POC gRPC server', 40);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-211 - gRPC: Creación de RI para gRPC', 40);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXEV-210 - INT: Métricas Debezium + kafka-connect con Prometheus + panel en Grafan', 40);
