INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 41, 309, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 42, 310, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 41, 311, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 41, 312, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 41, 313, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 41, 314, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 41, 315, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 41, 316, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 41, 317, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 41, 318, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 41, 319, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 43, 320, 'no adoptada aún en el proyecto');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio, Alberto', 7, 41, 321, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 43, 322, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 43, 323, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 43, 324, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 43, 325, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 43, 326, 'Prompt crear HU:Se aplicó para tener plantilla COMO, QUIERO, PARA con criterios de aceptación. (Hist');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 43, 327, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 43, 328, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 44, 329, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 43, 330, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 44, 331, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 44, 332, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 44, 333, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 44, 334, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 44, 335, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 44, 336, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 44, 337, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 44, 338, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 44, 339, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 44, 340, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 44, 341, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 45, 342, 'No es fiable al 100% hay que hacer un analisis funcional de la HU, modifiicar, añadir y eliminar tes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 45, 343, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 45, 344, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 46, 345, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 45, 346, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 45, 347, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 46, 348, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 46, 349, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 45, 350, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 45, 351, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 45, 352, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 353, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 45, 354, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio, Alberto', 7, 45, 355, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 356, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 45, 357, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 45, 358, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 359, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 45, 360, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 45, 361, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 362, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 45, 363, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 45, 364, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 45, 365, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 45, 366, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 46, 367, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 46, 368, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 7, 46, 369, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 370, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 46, 371, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 46, 372, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 46, 373, 'cambio minimo en la funcionalidad (añadir el botón exportar)');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 46, 374, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 375, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 46, 376, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 46, 377, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 46, 378, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 379, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 42, 380, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 381, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 382, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 383, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 384, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 7, 42, 385, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 385, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 42, 386, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 48, 387, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 48, 388, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 389, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 390, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 48, 391, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 48, 392, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alberto', 7, 42, 393, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 394, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran García', 7, 42, 395, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran Gámez', 7, 42, 396, 'No se ha usado prompts de Crear HU porque la información se ha sacado directamente del documento de ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 42, 397, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 42, 398, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 399, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 42, 400, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 42, 401, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 402, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 42, 403, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 404, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran', 7, 47, 405, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 406, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 407, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 408, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 409, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 410, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 411, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 412, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 413, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 414, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 415, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 416, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 417, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 418, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 47, 419, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 420, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 421, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 48, 422, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 48, 423, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 47, 424, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 425, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 48, 426, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 48, 427, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 428, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 429, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antonio', 7, 48, 430, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 48, 431, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael', 7, 48, 432, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 7, 47, 433, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ismael, Antonio', 7, 48, 434, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fran', 7, 48, 435, 'nan');
