INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-146 - Diseño de pruebas ALM módulo Gestión de Proyectos', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-148 - Corregir defecto endpoint registerProject', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-151 - FRONT. Gestión Delegados. Búsqueda y listado.', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-152 - FRONT. Gestión Delegados. Alta nuevo delegado', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-153 - FRONT. Gestión Delegados. Modificación delegado existente', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-154 - FRONT. Gestión Delegados. Baja delegado existente', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-155 - FRONT. Gestión Delegados. Detalle delegado existente', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-156 - Manual de usuario aplicación Web FDAR. Fase 1', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-157 - Automatización pruebas Módulo Configuración del FW', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-158 - Ejecución pruebas ALM módulo Gestión de proyectos en CER', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-159 - Desplegar en CER Módulo Gestión de proyectos', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-160 - Cobertura pruebas módulo Consultas de ejecuciones de pipelines', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-162 - Alineamiento aplicación Front FDAR (Bloque I) y test automatizados', 41);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-163 - FRONT. Gestión de entidades. Búsqueda y listado.', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-164 - FRONT. Gestión de entidades. Selector entidad', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-165 - FRONT. Gestión de entidades. Alta nuevo registro', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-166 - FRONT. Gestión de entidades. Modificación registro existente', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-167 - FRONT. Gestión de entidades. Baja registro existente', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-168 - Automatización pruebas Módulo Gestión de proyectos', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-169 - Desplegar en CER Módulo Delegados', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-170 - FRONT. Consultas ejecuciones pipelines. Exportar a Excel.', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-171 - Actualización Diseño Funcional - Exportar Excel Módulo Consultas', 43);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-172 - Mejoras accesibilidad. Resaltar módulo actual.', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-173 - Mejoras accesibilidad. Botón Volver en Buscador de Consultas', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-174 - Mejoras accesibilidad. Botón Volver en administración de entidad', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-175 - Desplegar en CER Módulo Gestión de entidades', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-176 - Desplegar en PRE Módulos finalizados y testeados', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-177 - Automatización pruebas Módulo Gestión de Delegados', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-178 - Diseño de pruebas ALM módulo Consultas ejecuciones pipelines.', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-179 - Diseño de pruebas ALM módulo Gestión de Delegados', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-180 - Eliminar registros duplicados de la tabla CONFIG_FW en el entorno de PRE', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-181 - Mejoras accesibilidad. Campos obligatorios.', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-182 - Nuevo endpoint exportación Excel Consultas de ejecuciones', 44);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-183 - Cobertura pruebas módulo Gestión de entidades', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-184 - Diseño de pruebas ALM módulo Gestión de entidades', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-185 - Ejecución pruebas ALM módulo Consultas de ejecuciones en CER', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-186 - Ejecución pruebas ALM módulo Delegados en CER', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-187 - Ejecución pruebas ALM módulo Entidades en CER', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-188 - Automatización pruebas Módulo Consulta ejecuciones', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-189 - Automatización pruebas Módulo Gestión de Entidades', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-190 - Actualización Diseño Funcional - Exportar Excel Resto de módulos', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-191 - Preparación Plantilla Plan Pruebas Rendimiento (Calidad)', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-192 - Nuevo endpoint exportación Excel Software', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-193 - Nuevo endpoint exportación Excel Agentes', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-194 - Nuevo endpoint exportación Excel Versiones por defecto', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-195 - Nuevo endpoint exportación Excel Configuraciones FW', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-196 - Nuevo endpoint exportación Excel Proyectos', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-197 - Nuevo endpoint exportación Excel Delegados', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-198 - Módulo Software. Exportar a Excel.', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-199 - Módulo Agentes. Exportar a Excel.', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-200 - FRONT. Módulo Versiones por defecto. Exportar a Excel', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-201 - Módulo Configuración FW. Exportar a Excel.', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-202 - Módulo Proyectos. Exportar a Excel.', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-203 - FRONT. Módulo Delegados. Exportar a Excel.', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-204 - Gestión entidades.  Actualizar validación campo descripción.', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-205 - Gestión delegados.  Selección de registro por clave única', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-206 - Nueva tabla parámetros de configuración FDAR', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-207 - Nuevo endpoint para la consulta de parámetros de configuración', 45);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-212 - FRONT. Selector entidad. Marcar por defecto primera categoría disponible.', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-213 - FRONT. Delegados. Marcar automáticamente flag "Todas las aplicaciones"', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-214 - FRONT. Desplegar en CER Nueva funcionalidad Exportación Excel', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-215 - Actualizacion CRUD Delegados.', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-216 - Exportación Excel. Imprimir correctamente el valor "Todos"', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-217 - Exportación Excel. Mantener orden de búsqueda seleccionado por el usuario.', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-218 - Cobertura pruebas nueva funcionalidad Exportación Excel', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-219 - Diseño de pruebas ALM funcionalidad Exportación a Excel', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-223 - Desplegar en CER, PRE Nueva funcionalidad Exportación Excel', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-224 - Actualizar secuenciadores ORACLE', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-225 - Ciclo PRE. Defecto 1. Logotipo sin funcionalidad', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-226 - Ciclo PRE. Defecto 4. Faltas de ortografía y errores gramaticales', 46);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-228 - Ciclo PRE. Defecto 5_1.  Botones que no cumple con su funcionalidad (Modificar)', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-231 - Ciclo PRE. Defecto 8_1.  Validación de campo (Email)', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-232 - Ciclo PRE. Defecto 8_2.  Validación de campo (Ruta Nexus)', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-233 - Ciclo PRE. Defecto 10.  Maquetación campos en pantallas de consulta', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-234 - Ciclo PRE. Defecto 11.  No se mantienen los ítems por página seleccionados.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-235 - Ciclo PRE. Defecto 2_1.  El puntero del ratón no cambio su apariencia (enlaces)', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-236 - Ciclo PRE. Defecto 2_2.  El puntero del ratón no cambio su apariencia (menú)', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-237 - Ciclo PRE. Defecto 3_1. Literales en pantalla o en mensajes que llevan a confusión (Campo no es válido).', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-238 - Ciclo PRE. Defecto 3_2.  Literales en pantalla o en mensajes que llevan a confusión (Resultados no encontrado).', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-239 - Ciclo PRE. Defecto 3_3. Literales en pantalla o en mensajes que llevan a confusión (Ya existe variable de entorno)', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-240 - Ciclo PRE. Defecto 3_4.  Literales en pantalla o en mensajes que llevan a confusión (El campo variable de entorno es obligatorio)', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-241 - Ciclo PRE. Defecto 3_5.  Literales en pantalla o en mensajes que llevan a confusión (El parámetro <name> no tiene un valor válido))', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-242 - Ciclo PRE. Defecto 7. Ausencia de mensajes', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-243 - Ciclo PRE. Defecto 9.  Campos que se marcan fuera de su radio de acción.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-245 - Introducir retraso en la ejecución de robotframework', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-246 - Defectos funcionalidad Exportación a Excel', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-247 - Reprobar defectos pruebas ALM Exportación Excel en CER', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-248 - Ciclo PRE. Revisar Defecto 5_2 y 6.', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-252 - Adaptación endpoint FADO: /query/getSoftware', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-253 - Adaptación endpoint FADO: /query/getAgentsBySoftware', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-254 - Adaptación endpoint FADO: /jobs/getDevOpsConfig', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-255 - Adaptación endpoint FADO: /jobs/getDevOpsConfigByJenkinType', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-256 - Adaptación endpoint FADO: /jobs/registerProject', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-257 - Adaptación endpoint FADO: /jobs/getProjectConfig', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-258 - Adaptación endpoint FADO: /jobs/logging', 42);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-259 - Adaptación endpoint FADO: /delegados/getDelegadosByCentroDesarrollo', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-260 - Actualización Plantilla Plan Pruebas Rendimiento (Nueva funcionalidad)', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-261 - Adaptación endpoint FADO: /jobs/getConfigAppByProject', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-269 - Adaptación endpoint FADO: /jobs/setConfigAppByProject', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-270 - Adaptación endpoint FADO: /jobs/queryProjectsByValues', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-271 - Adaptación endpoint FADO: /jobs/getConfigAppByProject', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-272 - Ciclo PRE. Vulnerabilidad. Defecto 37.  Datos de entrada inválidos. Caracteres inválidos', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-273 - Ciclo PRE. Vulnerabilidad. Defecto 38. Datos de entrada inválidos. Modificación no permitida.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-274 - Ciclo PRE. Accesibilidad. Defecto 12.  Información y relaciones. Falta de lista en el menú de navegación.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-275 - Ciclo PRE. Accesibilidad. Defecto 23. Idioma de las partes. Texto en diferente idioma.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-276 - Ciclo PRE. Accesibilidad. Defecto 13. Uso del color. Falta de cambios visuales en el menú al interactuar con el ratón', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-277 - Ciclo PRE. Accesibilidad. Defecto 14. Contenido no textual. Texto alternativo innecesario en una imagen decorativa.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-278 - Ciclo PRE. Accesibilidad. Defecto 15. Contenido no textual. Texto alternativo poco claro en imagen con enlace.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-279 - Ciclo PRE. Accesibilidad. Defecto 16. Información y relaciones. Encabezado de tabla vacío en un elemento <th>.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-280 - Ciclo PRE. Accesibilidad. Defecto 17. Foco visible. Icono de ordenación invisible.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-281 - Ciclo PRE. Accesibilidad. Defecto 18. Contenido no textual. Imagen decorativa.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-282 - Ciclo PRE. Accesibilidad. Defecto 19. Nombre, función, valor. Error de escritura del aria-label en el botón "Cerrar menú".', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-283 - Ciclo PRE. Accesibilidad. Defecto 20. Etiquetas o instrucciones. Duplicidad de nombres en los placeholder de campos de formulario.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-284 - Ciclo PRE. Accesibilidad. Defecto 21. Orientación. Doble scroll y texto entrecortado en ambas orientaciones.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-285 - Ciclo PRE. Accesibilidad. Defecto 22. Reflow. Doble scroll y texto entrecortado en áreas de visualización reducidas.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-286 - Ciclo PRE. Accesibilidad. Defecto 24. Foco visible. El combobox no recibe el foco visible del teclado.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-287 - Ciclo PRE. Accesibilidad. Defecto 25. Nombre, función, valor - Falta de descripción accesible en el botón de cerrar modal.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-288 - Ciclo PRE. Accesibilidad. Defecto 26. Procesamiento HTML.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-289 - Ciclo PRE. Accesibilidad. Defecto 27. Procesamiento HTML.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-290 - Ciclo PRE. Accesibilidad. Defecto 36. Abreviaturas . Falta de identificación de la abreviatura "SW".', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-291 - Ciclo PRE. Accesibilidad. Defecto 28. Nombre, función, valor - El lector de pantalla no lee las opciones del selector "Estado".', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-292 - Ciclo PRE. Accesibilidad. Defecto 29. Cambio del tamaño del texto. Uso de medidas absolutas para definir el tamaño de la fuente.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-294 - Ciclo PRE. Accesibilidad. Defecto 31. Cambio del tamaño del texto. Uso de medidas absolutas en el CSS. (icon.css, selector=".material-icons")', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-295 - Ciclo PRE. Accesibilidad. Defecto 32. Procesamiento HTML.', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-296 - Ciclo PRE. Accesibilidad. Defecto 33. Propósito de los enlaces. Texto de enlace insuficiente y redundante en el atributo title.', 47);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-301 - Desplegar en CER, PRE Nueva versión 1.1.4 (correcciones)', 48);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-302 - Preparación entorno paso a producción FDAR', 48);
