INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1164 - DSPPDSPP - Crear servicio público DSPPCOPE -"Consulta de permisos"', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1165 - DSPPDSPP - Añadir funcionalidad de detalle de grupo en el servicio "Consulta de permisos"', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1172 - DSPPDSPP - Modificar y reajustar pantallas en el servicio de consulta de histórico de listados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1173 - DSPPDSPP - Modificar pantalla de listados Modificar pantalla de listados de “Consulta de histórico de listados“ para permitir la descarga de varios listados seleccionados en un zip solamente en destinos centralizados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1176 - DSPPDSPP - Aplicar preferencias de usuario en la descarga en ZIP en Consulta de histórico listados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1180 - DSPPDSPP - Añadir funcionalidad al servicio "Consulta de permisos" para administradores de grupo', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1181 - DSPPDSPP - Añadir funcionalidad de detalle del destino en el servicio "Consulta de permisos" para administradores de grupo', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1182 - DSPPDSPP - HARA 87 - Corregir CSS Error de análisis sintáctico en estilos.css', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1183 - DSPPDSPP - HARA 88 - Modificar el title del enlace "Búsqueda informes" en Consulta de listados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1184 - DSPPDSPP - HARA 90 - Corregir id de atributos duplicados en Consulta de listados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1158 - AIFOADMI - Error por subsistema inexistente en el alta de aplicaciones en todos los entornos', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1187 - DSPPDSPP - HARA 96 - Eliminar mensaje prescindible en popup informes', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1188 - DSPPDSPP - HARA 95 - Modificar "Valor por defecto" en combo "Ordenar por" en consulta de listados e histórico', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1191 - DSPPDSPP - Añadir funcionalidad de consulta de permisos de impresoras en el servicio "Consulta de permisos"', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1194 - DSPPDSPP - Añadir funcionalidad de detalle de impresora en el servicio "Consulta de permisos"', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1195 - DSPPDSPP - HARA 97 - Preferencias de usuario. Modificar campo numero de filas para que no admita números negativos.', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1196 - DSPPDSPP - Añadir funcionalidad al servicio "Consulta de permisos" para administradores de impresora', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1199 - DSPPDSPP - HARA 98 - Gestión de grupos .El campo desplegable “Grupo” no se actualiza', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1202 - DSPPDSPP - HARA 99 - Corregir Nullpointer exception en consulta de listados, baja lógica', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1203 - DSPPDSPP - Añadir funcionalidad de detalle del destino en el servicio "Consulta de permisos" para administradores de impresora', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1206 - IFIWIFIW - Eliminar el sufijo "_signed.csig" del nombre del fichero', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1207 - DSPPDSPP - Corregir servicio de Configuración de columnas de listados/Consulta de listados', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1208 - DSPPDSPP - Corregir formulario de Configuración de columnas de listados para mantener datos al mostrar errores', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1209 - DSPPDSPP - Corregir formulario de Configuración de columnas de listados para mantener valores modificados al cambiar fila de posición', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1210 - DSPPDSPP - HARA 101 - Corregir altas en Gestión de grupos e impresoras para que no admita caracteres extraños', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1211 - DSPPDSPP - Corregir formulario de Configuración de columnas de listados para permitir caracteres especiales en nombres de columnas genéricas', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1223 - DSPPDSPP - Gestión de apuntes - Corregir maquetación, mensajes y validaciones de los campos.', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1235 - AIFOADMI - HARA 21 - Nullpointer en el servicio de Generación de script de migración', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1236 - AIFOADMI - Añadir validación javascript en el mantenimiento/consulta de formularios', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1241 - AIFOADMI - Modificar etiqueta Fecha de migración', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1244 - DSPPDSPP - Consulta de apuntes - Corregir maquetación, mensajes y validaciones de los campos.', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1248 - AIFOADMI - Error de validación javascript en los campos de búsqueda en el servicio de Gestión de paquetes', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1287 - IFIWIFIW - Migrar a WAS 9', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1296 - AIFOADMI - Desaparecen los campos Aplicación y Tecnología en el servicio de Gestión de paquetes', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1297 - AIFOADMI - Nullpointer al generar zip desde el servicio de Gestión de paquetes', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1298 - AIFOADMI - Corregir navegación después de dar de alta un formulario', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1299 - AIFOADMI - Correcciones en la gestión de sistemas y subsistemas', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1300 - IFIWIFIW - Homogeneizar búsqueda en las pestañas de descarga de ficheros y de histórico', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1307 - DSPPDSPP - HARA 41 (2) ,52 - Correcciones ortográficas en varios servicios', 49);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1308 - DSPPDSPP - HARA 102 Corregir perdida de valores en Gestión de usuarios.', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1309 - DSPPDSPP - HARA 103 Corregir perdida de documentación al paginar en Gestión de usuarios.', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1310 - DSPPDSPP - HARA 104 Corregir títulos cabeceras- Gestión de grupos/Gestión de usuarios', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1313 - DSPPDSPP - Rediseño configuración de columnas de listados, añadir nueva pantalla para editar nombre de columnas genérica', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1317 - DSPPDSPP - Migración a JUnit5 y paralelización del servicio Consulta de Usuarios', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1318 - DSPPDSPP - Migración de los tests de exportación JUnit5 a su propia clase', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1319 - DSPPDSPP - Corregir número de filas en Consulta de apuntes', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1337 - DSPPDSPP - Corregir número de filas en Consulta de histórico apuntes', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1340 - DSPPDSPP - Estandarizar validaciones de caracteres extraños (<>) ,validaciones en Consulta de grupos', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1341 - DSPPDSPP - Modificar servicio Configuración de columnas de listados, para permitir caracteres en descripción de Columnas', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1344 - DSPPDSPP - Modificar servicio Configuración de columnas de listados para que ponga configuración defecto con error de columnas', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1354 - AIFIADMI - Cambio de nombres de JNDI para adaptarse a WAS 9', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1363 - DSPPDSPP - Que número de días para ocultar  icono pdf sea configurable en el histórico de listados', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1364 - WSDPSWEB - Adecuar a las nuevas reglas críticas de kiuwan', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1367 - AIFIADMI - Corrección de reglas KIUWAN', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1368 - DSPPDSPP - Migración a JUnit5 y paralelización del servicio Gestión de Usuarios', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1372 - DSPPDSPP - Consulta de histórico de apuntes - Corregir maquetación, mensajes y validaciones de los campos.', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1373 - DSPPDSPP - Consulta de Configuración de Usuario- Corregir mensajes y validaciones del campo.', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1376 - DSPPDSPP - Consulta para desarroladores - Corregir maquetación, mensajes y validaciones de los campos.', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1377 - DSPPDSPP - Consulta preformato impresora - Estandarizar campos validaciones de caracteres extraños (<>,&..)', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1378 - DSPPDSPP - Gestión de administradores de grupo - Estandarizar campos validaciones de caracteres extraños (<>,&..)', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1379 - DSPPDSPP - Gestión de administradores delegados- Estandarizar campos validaciones de caracteres extraños (<>,&..)', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1385 - DSPPDSPP - Gestión de destinos - Estandarizar campos validaciones de caracteres extraños (<>,&..)', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1392 - SMNT - SMNTXMLT - Kiuwan proceso crearXmlTren', 50);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1393 - DSPPDSPP - Crear nuevo servicio XV21GW00 "Preferencias de usuario para desarrolladores"', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1396 - DSPPDSPP - Corregir DEINBASE-838 número de filas', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1403 - SMNT - SMNTWSIP - Incluir logs en Retina', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1404 - AIFOADMI - Modificación de la pantalla de asociación de componentes a formulario', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1405 - AIFIADMI - Agregar fecha de retirada a las transmisiones retiradas', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINTER-1155 - ESILMAQU - Eliminar campo NUEVA CLAVE en pantalla e-SIL para Conexiones Externas y redirigir a cambio de clave en POCE.', 51);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINTER-1161 - SMS0SMS0 - Registrar excepción de encolado en el log para visualizar en Retina.', 51);
