INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 436, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 437, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 438, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 439, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 440, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 441, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 442, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 443, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 444, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 445, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 446, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 447, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 448, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 449, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 450, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 451, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 452, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 453, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 454, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 455, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 456, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 457, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 458, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 459, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 460, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 461, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 462, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 463, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 464, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 465, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 466, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 467, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 468, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 469, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 470, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 471, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 472, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 49, 473, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 49, 474, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 475, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 476, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 477, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 478, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 479, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 480, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 481, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 482, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 483, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 484, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 485, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 50, 486, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 487, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 488, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 50, 489, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('David Corpas', 8, 50, 490, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 491, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 492, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 493, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 494, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 495, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 496, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 50, 497, 'Clone de otra HU');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristina Martín', 8, 50, 498, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 51, 499, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Moisés González', 8, 51, 500, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristina Martín', 8, 51, 501, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 51, 502, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Pedro Sánchez', 8, 51, 503, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Eloy Gil', 8, 51, 504, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Eloy Gil', 8, 51, 505, 'nan');
