INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', '1', '1', '1', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', '1', '1', '2', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', '1', '1', '3', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '1', '4', 'No usé IA para esta tarea porque solo tuve que tocar pequeñas configuraciones que me dijeron');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '1', '5', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '1', '6', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '1', '7', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '1', '8', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '1', '9', 'No aplica ya que se trata añadir endpoints a la propia securización ya existente.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '1', '10', 'No aplica debido a que había que identificar que endpoints eran necesario securizar.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '1', '11', 'Hacer test en una clase abstracta la instancia. Luego llama a un atributo como si fuera un método, y');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', '1', '1', '12', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', '1', '1', '13', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario / Andrea', '1', '1', '14', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '1', '15', 'En tareas de crear HU, documentar y comprensión de código muy buenos resultados, pero a la hora de d');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '1', '16', 'Es cambiar el nombre del secreto y probar las RIs ya desplegadas, no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '1', '17', 'Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '1', '18', 'Pasó el análisis kiuwan con todo correcto, por lo que no hizo falta la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '19', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '20', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '21', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '22', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '23', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '24', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '25', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '26', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '27', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '1', '28', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '2', '29', 'Usada para una primera aproximación de cobertura de pruebas.El resultado es bastante preciso, pero r');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '2', '30', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '2', '31', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '2', '32', 'No aplica en este caso.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '2', '33', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '2', '34', 'El cambio a realizar era demasiado evidente y sencillo como para hacer uso de la IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '2', '35', 'Utilizada para la generación de pruebas con Mockito y Junit');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '2', '36', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '2', '37', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '2', '15', 'Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '2', '38', 'Las respuesta de la IA no era correcta, contrastando información con webs no se podía hacer.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '2', '39', 'Aplicada para hacer los test unitarios y refactorizar el código');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '2', '40', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '2', '41', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', '1', '3', '42', 'Se ha utilizado IA para facilitar la realización de los tests.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '3', '43', 'Se ha utilizado para extraer cobertura, ha requerido revisión y modificación.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '3', '44', 'Se ha utlizado la IA para que proporcione información y detalle acerca del funcionacimiento de la BB');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', '1', '3', '45', 'Debido a el ambito de la tarea, subiendo a la version 3.3.2 de springboot, no se a podido utilizar i');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '3', '46', 'Fue una migración de jdk17 a 21 la cual no tuvo mucha complejidad ni tuvo que tocar código.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '3', '47', 'Realmente en esta tarea no he usado IA porque tenía que dividir una RI en dos RIs, por lo que el cód');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '3', '48', 'Me ha servido la IA para ayudarme a enforcar ciertos problemas de la tarea. Creo que la podría haber');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '3', '49', 'Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '3', '50', 'Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '3', '51', 'No ha hecho falta el uso de IA ya que la tara solo consistía en desplegar dos RIs de entirex en prep');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '3', '52', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '3', '36', 'Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '3', '53', 'Utilizada para refactorización de un trozo de código que lo hace mas legible y sencillo.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '3', '54', 'Añadidos nuevos métodos en RequestBytesService y sus test unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '3', '55', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '3', '56', 'Tests unitarios de las nuevas funcionalidades del RequestService en el framework');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '3', '57', 'Inclusión de los reintentos y envío de la DLT en Kafka RequestService');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '3', '58', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '3', '59', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '3', '60', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '3', '54', 'El código es muy jerárquico con mucha abastracción. Los prompts están diseñados para desarrollos más');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '4', '61', 'Eran unos defectos que venian del sprint anterior, por lo que ya estaba todo diseño y ejecutado, sol');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '62', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '4', '36', 'Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '63', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '45', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '4', '64', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '4', '65', 'Se ha utilizado para consultar y aclarar los endpoint y para que nos indicara como preparar los jueg');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '66', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', '1', '4', '67', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '4', '68', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', '1', '4', '69', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '4', '70', 'Se ha utilizado para ver que camino era el adecuado al utilizar una función dentro del código.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '4', '71', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '4', '72', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '4', '73', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '4', '74', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '4', '75', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '76', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', '1', '4', '77', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '4', '78', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '4', '79', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', '1', '4', '80', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '4', '63', 'Cuando el código aumenta en abastracción y jerarquí se necesitan prompts/modelos más potentes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos / Antoni / Alvaro', '1', '4', '81', 'No usa IA ya que solo hay que cambiar la versión de las RIs y desplegar');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '4', '76', 'Fue util para entender el código y resolver ciertas dudas en general. Me ayudó mucho a generar los t');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', '1', '4', '62', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '4', '82', 'Una tarea de investigación la cual se tenía previamente enlaces de interés en los que venía varias s');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '5', '83', 'Se hizo uso de IA en la documentación del código y en las pruebas unitarias, aunque el resultado no ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '5', '84', 'No se ha usado porque se conocía la causa y una posible viabilidad.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '5', '85', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '5', '86', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '5', '87', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '5', '88', 'Utilizada la IA para la ocbertura de casos de prueba, los resultados son bastantes correctos, sobre ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '5', '83', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '5', '84', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '5', '89', 'Utilizada para Test y para comprender el uso de métricas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '5', '90', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', '1', '5', '91', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', '1', '5', '92', 'Se ha aplicado la IA de forma satisfactoria en la creación de scripts destinados a modificar ciertos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '5', '93', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', '1', '5', '9', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '5', '94', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '5', '95', 'Para esta tarea no necesité IA porque realmente era darse cuenta de que los drivers estaban desactua');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '5', '96', 'Para la ejecución manual de los test no automatizados no se ha requerido el uso de la IA, ya que los');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '5', '97', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '5', '98', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '5', '99', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '5', '100', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '5', '101', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '5', '102', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '5', '103', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', '1', '5', '104', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '5', '105', 'Se usa para la IA cobertura de pruebas y para realizar consultas de los posibles motivos de que se m');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', '1', '5', '106', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', '1', '5', '107', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '5', '108', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '5', '109', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', '1', '5', '110', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', '1', '6', '111', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', '1', '6', '112', 'Debido al tipo de correcciones a realizar, no ha sido necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', '1', '6', '113', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '6', '114', 'La tarea principal consistía en analizar cómo añadir en el framework una nueva feature y la IA fue ú');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '6', '115', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '6', '116', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', '1', '6', '117', 'Constaba de probar las RIs en integración por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '6', '118', 'En esta tarea he utilizado muchísimo la IA para lenvantar la consola y registrar las aplicaciones de');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '6', '119', 'Aplica lo mismo que en el análisis, no se ha usado porque se conocía la causa y una posible viabilid');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '6', '120', 'Se facilitaron docs y comentarios para resolver este problema.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '6', '121', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '6', '122', 'Usé realmente la IA para los tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '6', '123', 'IA utilizada para algunas partes del analisis realizado, pero no aplica uso de los prompts existente');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', '1', '6', '124', 'IA utilizada para dudas en código groovy,pero no aplica el uso de prompts existentes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '6', '93', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '6', '125', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '6', '126', 'Usada IA para aclaración y explicación de unas cabeceras obtenidas en un microservicio en el campo C');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario ', '1', '6', '127', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario ', '1', '6', '128', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '6', '129', 'Creación de HU usando IA , el resultado es bastante preciso y correcto, se necesitan hacer algunas m');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', '1', '6', '130', 'Analisis de las salidas de prometheus. Petición de algoritmo.  Test (36 hoaras con ira, 40 sin IA)');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', '1', '7', '131', 'Gracias a las documentaciones que tenía a mano no necesité usar en este caso la IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '7', '132', 'No he necesitado IA. Solo documentación y mirar ejemplos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '7', '133', 'No se ha necesitado IA ya que estan tareas correspondian a ejecución de pruebas ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', '1', '7', '134', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '135', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '136', 'Tarea de pruebas, no aplica IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '137', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '138', 'Tarea de soporte para crear una nu8eva pipeline en jenkins, no aplica IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '7', '139', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', '1', '7', '140', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '141', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '142', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', '1', '7', '143', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', '1', '7', '144', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', '1', '7', '145', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni-Rafa', '1', '7', '146', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '147', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '148', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '149', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '150', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', '1', '7', '151', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', '1', '7', '152', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', '1', '7', '153', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '154', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '155', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '156', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '157', 'Inframail no soporta HTML, por lo que el uso de IA no ha hecho falta aquí debido a que se solicitó s');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '158', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '159', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '160', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '161', 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', '1', '7', '162', 'nan');
