INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-877 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-907 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-912-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-916 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-903 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-909 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-910-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-911-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-897 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-914 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-933-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-862 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-864 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-550 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-545 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-904 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-905 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-908 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-919 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-920 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-921 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-923 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-926 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-930 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-932-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-937-Testing - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-945 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-948 - ', 52);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-974-Testing - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-947 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-973 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-952 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-962-Testing - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-917 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-949 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-950 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-485 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-906 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-956-Testing - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-944 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-946 - ', 53);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DANAUA-618 - [APNA] Actualización NauaCLI a última versión por commandline', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1014-Testing - [Testing] Fase II - Pruebas desarrollos RI Cola MQ', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1030-Testing  - [Testing] Cobertura, diseños de casos en ALM y Pruebas de operaciones en caché con MongoDb', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-980 - Subir versión de Spring Boot a la 3.3.2', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1015 - [APNA] Fase II - Pruebas Onbo', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1029 - Separar la RI  ot_nauamqse_ri-mqseries (productor/consumidor) MQ, en un productor y un consumidor', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1034 - Modifiicar la Configuración del componente LongRunningAction para fijar enable-auto-commit a false, max-poll-records a 1', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1000 - Fase I - Starter S3: funcionalidades basicas', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1009 - Creación de RI con starter S3', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-975 - Fase II - Pasar RIs EntireX a CER y PRE y crear planes de prueba', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-957 - [Testing Automatización] Automatizar casos de RestClient', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-988 - Corregir configuración Kafka para comprobar si existe seguridad antes de buscar usuario', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1021 - Fase II - Implementación Long Running Kafka', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1022 - Participante Start crea el traceId común y lo añade a la cabeceras del LRA', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1018 - Test unitario RequestService', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1019 - Fase II - Tests unitarios - Inclusión configuración reintentos y dlt en kafka request', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-989 - Añadir java_opts custom por parte del proyecto al deployment', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-987 - Añadir propiedad en RestClient para configurar tamaño maximo payload', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-992 - Analisis error en generación de Swagger a partir de un OpenAPI yml', 54);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1055 - [Testing] Cobertura, diseños de casos en ALM y Pruebas de operaciones en caché con MongoDb', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1056 - [ALM] Revisión de la Poc Cache MongoDb para un correcto funcionamiento', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1002 - Fase I - Implementación observabilidad LRA coordinator: Logs y Trazas agregados', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1028 - Análisis para la posible implementación de un Starter SOAP', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1047 - [Testing] Pruebas RI S3', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-943 - [Testing Automatización] Automatizar casos de Resiliencia', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1046 - Obtención credenciales de secreto para llamar curl desde NauaCli', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1041 - Pruebas nueva versión de FW DevOps y Chart de java', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1035 - Realizar una RI de un consumidor Kafka de larga duración para probar el componente LongRunningConsumer', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1043 - Creación/modificación gissWebApiClient llamada ApiConnect + ApplicationId', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1038 - Crear constructor con todos los campos para clase GissErrorResponse', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1071 - Añadir validaciones en operaciones S3', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1053 - Activar trazas en Starter S3', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1052 - Añadir opciones de filtrado en operación listObjects de starter s3', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1051 - Añadir configuración de reintentos en clientes S3', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1050 - Añadir nueva propiedad para endpoints adicionales securizados', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1064 - [ALM] Corrección de defecto en cache Mongodb (tarea DENAUA-1036)', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1058 - [Testing Automatización] Automatizar casos de la Gestión de Errores en Batch', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1065 - [Soporte] Incluir centro de desarrollo UP', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1066 - Ampliación funcionalidad RI Kafka Producer para envío evento a Consumer Long Running', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1074 - Actualización de RIs a versión NAUA con Spring Boot 3.3.2', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1068 - Corregir configuración Swagger para URL generada del servidor', 55);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1070 - Creación API Mock carga inicial para NAUF según contrato acordado', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1098 - Análisis de refactor en filtros JPA para valores múltiples', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1108 - Pruebas configuración de reintentos en clientes S3', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1096 - Añadir validaciones de extensión en clientes s3', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1099 - Análisis de refactor en filtros MongoDB para valores múltiples', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1107 - Testing Fase II-Pruebas RI S3', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1089 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1085 - Implementar en fw de devops lanzamiento chart LRA en base a flag en el values', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1039 - Análisis refactor clase AuditableEntity de jpa y AuditableDocumentEntity de Mongo ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1082 - Actualización Version Java a la 21 con la ayuda de scripts', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1048 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1128 - Observabilidad SAGA, validar el correcto funcionamiento de las Trazas emitidas por la Observabilidad de la Saga', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1109 - Compatibilidad versión de Spring Boot 3.3.2 y MongoDB', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1102 - Ejecución manual de los test no automatizados', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1100 - Pruebas Automaticas Framework NAUA', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1084 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1129 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1078 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1080 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1049 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1135 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1101 - Refactorización de la clase WService ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1095 - LKR LongRunning consumer', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1110 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1131 - Pruebas RI Kafka Rquest/Replay', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1141 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1142 - ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1145 - Añadir la cabecera X-GISS-REPRESENTATION al filtro que traspasa las cabeceras a los restclient ', 56);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1204 - Eliminacion de contraseñas guardadas en NauaCli', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1161 - Corrección defecto en RI multipledb', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1060 - Mejoras de algunos metodos de NauaCli', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1150 - Análisis + Poc viabilidad de starter JPA pasra permitir filtrado múltiple OR', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-735 - Análisis funcionalidad incluir recuento total de elementos en las colecciones en el framework', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1149 - Implementación de filtrado de múltiples valores en starter Mongo', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1206 - Prueba de RI Avo con nueva versión de Event Streams en integración', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1045 - Consola Batch (Spring Cloud Data Flow): Creación y seguimiento issue comunidad Spring Batch5', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1148 - Implementación de filtrado de múltiples valores en starter JPA', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1033 - Analizar resultado del análisis  de sostenibilidad realizado por el equipo de observabilidad y aplicar corrección', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1147 - Análisis métricas batch', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1124 - Cambio en metodo checkversion seteo dinamico ruta Nauacli', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1011 - Análisis arquitectura para la implementación del endpoint InitialLoading para proyectos Front', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1137 - Modificación FW DEVOPS para adaptación del lanzamiento del chart Kafka a nuevos clusters en la nube (nuevo parámetro Cluster ID)', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-828 - Análisis lanzamiento de job desde control-m y kafka', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1207 - [Testing] Validar la funcionalidad de la ri ot_nauawcli_ri-web-client.', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1188 - [Testing] Revisión casos, rediseño y pruebas por el cambio en la RI Cache Mongo ', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1138 - [Testing] Pruebas de la RI ot_nauamult_ri_multipledb', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1201 - [Testing] Ri Security 3', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1190 - ', 57);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1211 - Análisis del uso de Chaos Monkey como herramienta de Testing para la mejora de las pruebas de Resilencia', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-915 - Incorporar Avro en el request_replay entre los servicos ot_apnarsql_request-service-layered y ot_apnarsql_reply-service-layered', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1164 - [Testing] Fase II - Validar la funcionalidad de la ri ot_nauasec2_ri-security2 (ejecución pruebas)', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1236 - [Testing] Validar la funcionalidad de la ri ot_nauasec3_ri-security3 - Fase II: Pruebas', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1239 - Analizar resultado del análisis de sostenibilidad realizado por el equipo de Observabilidad y aplicar corrección - Fase II: Pruebas Observabilidad', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1259 - Modificación FW DEVOPS para adaptación del lanzamiento del chart Kafka a nuevos clusters en la nube (nuevo parámetro Cluster ID) - Fase II: Pruebas', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1237 - SOPORTE: Analizar el componente LongRunningConsumerService que no detiene el consumo, por PASS en Pensiones - Fase II: Pruebas Pensiones', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1260 - Soporte creacion pipeline despliegue Kafka Connect INT', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-865 - Creación chart para desplegar aplicación batch como Cronjob y pruebas', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1329 - Actualizar Framework DevOps para lanzar chart cronjob', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1088 - Lanzar un job desde LRAAsynchronous Batch Launcher', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1238 - Diagnóstico de errores en comandos lanzados desde chart Kafka en AWS', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1205 - Inclusión de label con tallaje utilizado en el microservicio en chart java', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1223 - Adición de la información mostrada en los labels como variables de entorno en chart Java', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1224 - Mostrar en logs las variables de entorno que contienen la información de los labels', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1175 - Implementación Starter MQZ - Fase I', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1265 - Añadir adaptador Rest al microservicio certification de APNA', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1156 - Incluir nuevas métricas arenas (1/3) Nueva imagen añadiendo JavaPmapInspector', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1157 - Incluir nuevas métricas arenas (2/3) - Crear script', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1158 - Incluir nuevas métricas arenas (3/3) - Configurar tarea @Scheduled en framework', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1162 - Aplicación nueva versión chart Java en RIs y probar las Ris', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1212 - Creación de RI BFF', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1213 - Estudio de clases, dependencias y propiedades comunes a los BFF para posterior inclusión en NAUA-Generator', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1220 - Pruebas de ingesta de métricas de microservicio NAUA en DynaTrace', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1209 - Filtrado de campos fecha en Jpa', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1246 - Creación de un microservicios NAUA de pruebas para DevOps', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1216 - Analizar funcionalidad de incorporarar', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1187 - [Testing Automatización] Componente que gestiona Cache Mongo (II)', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1242 - [Testing Automatización] Componente que gestiona MQSeries', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1247 - [Testing Automatización] Componente que gestiona Multipledb', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1254 - [Testing Automatización] Componente que gestiona WebClient', 58);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1258 - [Testing] Validar la funcionalidad de la ri ot_nauawscl_ri-wsclient', 58);
