INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', 9, 52, 506, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', 9, 52, 507, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', 9, 52, 508, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 52, 509, 'No usé IA para esta tarea porque solo tuve que tocar pequeñas configuraciones que me dijeron');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 52, 510, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 52, 511, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 52, 512, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 52, 513, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 52, 514, 'No aplica ya que se trata añadir endpoints a la propia securización ya existente.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 52, 515, 'No aplica debido a que había que identificar que endpoints eran necesario securizar.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 52, 516, 'Hacer test en una clase abstracta la instancia. Luego llama a un atributo como si fuera un método, y');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 9, 52, 517, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 9, 52, 518, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario / Andrea', 9, 52, 519, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 52, 520, 'En tareas de crear HU, documentar y comprensión de código muy buenos resultados, pero a la hora de d');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 52, 521, 'Es cambiar el nombre del secreto y probar las RIs ya desplegadas, no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 52, 522, 'Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 52, 523, 'Pasó el análisis kiuwan con todo correcto, por lo que no hizo falta la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 524, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 525, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 526, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 527, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 528, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 529, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 530, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 531, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 532, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 52, 533, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 53, 534, 'Usada para una primera aproximación de cobertura de pruebas.El resultado es bastante preciso, pero r');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 53, 535, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 53, 536, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 53, 537, 'No aplica en este caso.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 53, 538, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 53, 539, 'El cambio a realizar era demasiado evidente y sencillo como para hacer uso de la IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 53, 540, 'Utilizada para la generación de pruebas con Mockito y Junit');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 53, 541, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 53, 542, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 53, 520, 'Son pruebas de ejecución de concurrencia en siegue por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 53, 543, 'Las respuesta de la IA no era correcta, contrastando información con webs no se podía hacer.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 53, 544, 'Aplicada para hacer los test unitarios y refactorizar el código');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 53, 545, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 53, 546, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', 9, 54, 547, 'Se ha utilizado IA para facilitar la realización de los tests.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 54, 548, 'Se ha utilizado para extraer cobertura, ha requerido revisión y modificación.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 54, 549, 'Se ha utlizado la IA para que proporcione información y detalle acerca del funcionacimiento de la BB');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', 9, 54, 550, 'Debido a el ambito de la tarea, subiendo a la version 3.3.2 de springboot, no se a podido utilizar i');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 54, 551, 'Fue una migración de jdk17 a 21 la cual no tuvo mucha complejidad ni tuvo que tocar código.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 54, 552, 'Realmente en esta tarea no he usado IA porque tenía que dividir una RI en dos RIs, por lo que el cód');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 54, 553, 'Me ha servido la IA para ayudarme a enforcar ciertos problemas de la tarea. Creo que la podría haber');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 54, 554, 'Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 54, 555, 'Se ha utilizado para acelerar la creación de HU y la realización de tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 54, 556, 'No ha hecho falta el uso de IA ya que la tara solo consistía en desplegar dos RIs de entirex en prep');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 54, 557, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 54, 541, 'Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 54, 558, 'Utilizada para refactorización de un trozo de código que lo hace mas legible y sencillo.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 54, 559, 'Añadidos nuevos métodos en RequestBytesService y sus test unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 54, 560, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 54, 561, 'Tests unitarios de las nuevas funcionalidades del RequestService en el framework');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 54, 562, 'Inclusión de los reintentos y envío de la DLT en Kafka RequestService');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 54, 563, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 54, 564, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 54, 565, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 54, 559, 'El código es muy jerárquico con mucha abastracción. Los prompts están diseñados para desarrollos más');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 55, 566, 'Eran unos defectos que venian del sprint anterior, por lo que ya estaba todo diseño y ejecutado, sol');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 567, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 55, 541, 'Se han realizado pruebas en el entorno de FOR con la instancia de kafka disponible, ha sido algo mas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 568, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 550, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 55, 569, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 55, 570, 'Se ha utilizado para consultar y aclarar los endpoint y para que nos indicara como preparar los jueg');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 571, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', 9, 55, 572, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 55, 573, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 9, 55, 574, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 55, 575, 'Se ha utilizado para ver que camino era el adecuado al utilizar una función dentro del código.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 55, 576, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 55, 577, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 55, 578, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 55, 579, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 55, 580, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 581, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', 9, 55, 582, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 55, 583, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 55, 584, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 9, 55, 585, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 55, 568, 'Cuando el código aumenta en abastracción y jerarquí se necesitan prompts/modelos más potentes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos / Antoni / Alvaro', 9, 55, 586, 'No usa IA ya que solo hay que cambiar la versión de las RIs y desplegar');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 55, 581, 'Fue util para entender el código y resolver ciertas dudas en general. Me ayudó mucho a generar los t');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Álvaro', 9, 55, 567, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 55, 587, 'Una tarea de investigación la cual se tenía previamente enlaces de interés en los que venía varias s');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 56, 588, 'Se hizo uso de IA en la documentación del código y en las pruebas unitarias, aunque el resultado no ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 56, 589, 'No se ha usado porque se conocía la causa y una posible viabilidad.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 56, 590, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 56, 591, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 56, 592, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 56, 593, 'Utilizada la IA para la ocbertura de casos de prueba, los resultados son bastantes correctos, sobre ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 56, 588, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 56, 589, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 56, 594, 'Utilizada para Test y para comprender el uso de métricas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 56, 595, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 9, 56, 596, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', 9, 56, 597, 'Se ha aplicado la IA de forma satisfactoria en la creación de scripts destinados a modificar ciertos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 56, 598, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alvaro', 9, 56, 514, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 56, 599, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 56, 600, 'Para esta tarea no necesité IA porque realmente era darse cuenta de que los drivers estaban desactua');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 56, 601, 'Para la ejecución manual de los test no automatizados no se ha requerido el uso de la IA, ya que los');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 56, 602, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 56, 603, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 56, 604, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 56, 605, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 56, 606, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 56, 607, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 56, 608, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 9, 56, 609, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 56, 610, 'Se usa para la IA cobertura de pruebas y para realizar consultas de los posibles motivos de que se m');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Cristian', 9, 56, 611, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario', 9, 56, 612, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 56, 613, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 56, 614, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Alejandro', 9, 56, 615, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', 9, 57, 616, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', 9, 57, 617, 'Debido al tipo de correcciones a realizar, no ha sido necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni', 9, 57, 618, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 57, 619, 'La tarea principal consistía en analizar cómo añadir en el framework una nueva feature y la IA fue ú');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 57, 620, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 57, 621, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rubén', 9, 57, 622, 'Constaba de probar las RIs en integración por lo que no es necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 57, 623, 'En esta tarea he utilizado muchísimo la IA para lenvantar la consola y registrar las aplicaciones de');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 57, 624, 'Aplica lo mismo que en el análisis, no se ha usado porque se conocía la causa y una posible viabilid');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 57, 625, 'Se facilitaron docs y comentarios para resolver este problema.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 57, 626, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 57, 627, 'Usé realmente la IA para los tests unitarios');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 57, 628, 'IA utilizada para algunas partes del analisis realizado, pero no aplica uso de los prompts existente');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('René', 9, 57, 629, 'IA utilizada para dudas en código groovy,pero no aplica el uso de prompts existentes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 57, 598, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 57, 630, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 57, 631, 'Usada IA para aclaración y explicación de unas cabeceras obtenidas en un microservicio en el campo C');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario ', 9, 57, 632, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Mario ', 9, 57, 633, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 57, 634, 'Creación de HU usando IA , el resultado es bastante preciso y correcto, se necesitan hacer algunas m');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Fernando', 9, 57, 635, 'Analisis de las salidas de prometheus. Petición de algoritmo.  Test (36 hoaras con ira, 40 sin IA)');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Daniel', 9, 58, 636, 'Gracias a las documentaciones que tenía a mano no necesité usar en este caso la IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 58, 637, 'No he necesitado IA. Solo documentación y mirar ejemplos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 58, 638, 'No se ha necesitado IA ya que estan tareas correspondian a ejecución de pruebas ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Andrea', 9, 58, 639, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 640, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 641, 'Tarea de pruebas, no aplica IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 642, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 643, 'Tarea de soporte para crear una nu8eva pipeline en jenkins, no aplica IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 58, 644, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carmen', 9, 58, 645, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 646, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 647, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', 9, 58, 648, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', 9, 58, 649, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', 9, 58, 650, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Antoni-Rafa', 9, 58, 651, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 652, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 653, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 654, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 655, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Carlos', 9, 58, 656, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Rafa', 9, 58, 657, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Ruben', 9, 58, 658, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 659, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 660, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 661, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 662, 'Inframail no soporta HTML, por lo que el uso de IA no ha hecho falta aquí debido a que se solicitó s');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 663, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 664, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 665, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 666, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 9, 58, 667, 'nan');
