INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 670, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 671, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 672, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 74, 673, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 74, 674, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 74, 675, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 676, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 677, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 678, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 679, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 680, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 12, 73, 681, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 75, 682, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 76, 683, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 76, 684, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 76, 685, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 76, 686, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 76, 687, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 77, 688, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 78, 689, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 77, 688, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 12, 78, 690, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 79, 691, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 79, 692, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 79, 693, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 694, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 695, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 696, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 697, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 698, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 699, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 81, 700, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 701, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 702, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 703, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 704, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 705, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 80, 706, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 12, 81, 707, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 82, 708, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 82, 709, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 710, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 711, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 712, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 713, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 714, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 715, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 716, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 717, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 718, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 719, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 720, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 12, 83, 721, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 84, 722, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 723, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 724, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 725, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 726, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 727, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 84, 728, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 729, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 12, 85, 730, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 12, 84, 731, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 12, 85, 732, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 12, 84, 733, 'nan');
