INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 670, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 671, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 672, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 61, 673, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 61, 674, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 61, 675, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 676, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 677, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 678, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 679, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 680, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROSSELLI TRINDADE', 11, 60, 681, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 62, 682, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 63, 683, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 63, 684, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 63, 685, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 63, 686, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 63, 687, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 64, 688, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 65, 689, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 64, 688, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('FERNANDO MORALEDA', 11, 65, 690, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 66, 691, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 66, 692, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 66, 693, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 694, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 695, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 696, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 697, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 698, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 699, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 68, 700, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 701, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 702, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 703, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 704, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 705, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 67, 706, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIEGO SANCHEZ', 11, 68, 707, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 69, 708, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 69, 709, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 710, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 711, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 712, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 713, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 714, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 715, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 716, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 717, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 718, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 719, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 720, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA VICTORIA GARCIA', 11, 70, 721, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 71, 722, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 723, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 724, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 725, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 726, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 727, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 71, 728, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 729, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TROYANO', 11, 72, 730, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 11, 71, 731, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 11, 72, 732, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ROBERTO PUERTAS', 11, 71, 733, 'nan');
