INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 86, 734, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 86, 735, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ELIZABETH SIMOES FERNANDES', 13, 86, 736, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ELIZABETH SIMOES FERNANDES', 13, 86, 737, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ELIZABETH SIMOES FERNANDES', 13, 86, 738, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 86, 739, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 86, 740, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 86, 741, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 86, 742, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 86, 743, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 86, 744, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 86, 745, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 746, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 747, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 87, 748, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 749, 'La IA documenta bastante bien aunque si son varios ficheros y poco a documentar el tiempo aumenta en');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 750, 'No aplica la utilización de la IA es configuración del workspace');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CATALINA CANGAS PEREZ', 13, 87, 751, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 752, 'No aplica la utilización de la IA  es eliminación de código que ya no se utiliza');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CATALINA CANGAS PEREZ', 13, 87, 753, 'He aplicado la IA para la generacion de casos de prueba.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CATALINA CANGAS PEREZ', 13, 87, 754, 'He aplicado la IA para la generacion de casos de prueba.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CATALINA CANGAS PEREZ', 13, 87, 755, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 756, 'No aplica la utilización de la IA  es e son instalaciones manuales dentro del escritorio virtual');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 87, 757, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 87, 758, 'No aplica la utilización de la IA, en la configuración del workspace');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 87, 759, 'Es una migración que se hace manualmente y no es necesario usar la IA.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 760, 'No aplica la utilización de los prompts  es revisión de documentación');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 87, 761, 'No aplica la utilización de la IA es configuración del workspace');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 762, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 87, 763, 'Usada para mejorar el javadoc de la clase afectada');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 764, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 765, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 766, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 767, 'Es un cambio muy controlado en una query por lo que no se pudo utilizar la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 87, 768, 'No aplica la utilización de la IA  es eliminación de código que ya no se utiliza');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 87, 769, 'No se ha utilizado la IA, debido a que la documentación de las clases se ha ido haciendo mientras se');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 87, 770, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 87, 771, 'Usada para partir de un código similar de otro servicio y adaptarlo a esta tarea');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 87, 772, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 88, 773, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 88, 774, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 88, 775, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CRISTIAN RODRIGUEZ RODRIGUEZ', 13, 88, 776, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CRISTIAN RODRIGUEZ RODRIGUEZ', 13, 88, 777, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CRISTIAN RODRIGUEZ RODRIGUEZ', 13, 88, 778, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 88, 779, 'útil para migrar al formato Creole aunque con bastantes fallos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 88, 780, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('CRISTIAN RODRIGUEZ RODRIGUEZ', 13, 88, 781, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('Benjamin', 13, 88, 782, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 88, 783, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 88, 784, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 88, 785, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 88, 786, 'Se usa IA para consultas rápidas (perfectamente realizables desde stack Overflow y otras) porque ofr');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MANUEL ZAPATERO RODRIGUEZ', 13, 88, 787, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 88, 788, 'Se usa IA para consultas rápidas (perfectamente realizables desde stack Overflow y otras) porque ofr');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 88, 789, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 88, 790, 'Útil para documentar métodos y generar un dummy para pruebas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 88, 791, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 88, 792, 'Útil para documentar métodos y generar un dummy para pruebas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 88, 793, 'Se usa IA para consultas rápidas (perfectamente realizables desde stack Overflow y otras) porque ofr');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 794, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 795, 'Para hacer las HU se ha usado en los primeros casos y luego se han usado de plantilla para el resto.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 796, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 797, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 798, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 799, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 800, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 801, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 802, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 803, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 804, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 805, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 806, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 807, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 808, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 809, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 89, 810, 'Se consulto la IA para desarrollar un PL/SQL pero al final la solución nos la proporciono Ramon');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('No asignado', 13, 90, 811, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 90, 812, 'No se ha requerido IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 90, 813, 'Son cambios concretos y definidos, solo usada en javadoc');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 90, 814, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 815, 'Es un cambio simple y muy controlado');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MANUEL ZAPATERO RODRIGUEZ', 13, 90, 816, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MANUEL ZAPATERO RODRIGUEZ', 13, 90, 817, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 818, 'Son script generados con prosaedi');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 90, 819, 'En esta tarea no era necesario el uso de la IA, porque solo se debía de cambiar un literal');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 820, 'Se ha utilizado la IA para analizar el error y poder dar solución');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 821, 'Es un cambio simple y muy controlado');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 90, 822, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('No asignado', 13, 90, 823, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 90, 824, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('No asignado', 13, 90, 825, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 90, 826, 'El cambio que se debía de hacer, no era necesario el uso de la IA');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 90, 827, 'Usada principalmente para refactorizar métodos y optimizar el código');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 90, 828, 'Tarea en curso.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 90, 829, 'Tarea en curso.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 90, 830, 'Son cambios concretos y definidos, solo usada en javadoc');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 90, 831, 'Se ha utilizado la IA, para la generación de una querry similar a que se necesitaba aplicar en el de');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 832, 'Son script generados con prosaedi');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 90, 833, 'Se ha utilizado la IA para documentar los cambios, pero no se ha utilizado más porque a que dar le c');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 90, 834, 'Es un cambio controlado donde se aplica una condición concreta. Aplicar la IA en este caso sería con');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 90, 835, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 90, 836, 'Se ha utilizado para documentar código y javadoc facilitando una plantilla de la clase a documentar.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 90, 837, 'Se ha utilizado la IA para documentar y refactorizar el codigo existente');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 90, 838, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 90, 839, 'Tarea en curso');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 90, 772, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 91, 840, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JOSE LUIS GONZALEZ ALAMO', 13, 91, 841, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 91, 842, 'He creado un promt para que me comparara la lista de ficheros en cada análisis kiuwan y me diera la ');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 91, 843, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 91, 844, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 91, 845, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 91, 846, 'Útil para documentar métodos y generar un dummy para pruebas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 91, 847, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 91, 789, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 91, 791, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 91, 793, 'Se usa IA para consultas rápidas (perfectamente realizables desde stack Overflow y otras) porque ofr');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANTONIO JOSE SEGOVIA', 13, 92, 848, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGAR ALEXANDER ESPIN', 13, 92, 849, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVAR ARGUDO', 13, 92, 850, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVAR ARGUDO', 13, 92, 851, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGAR ALEXANDER ESPIN', 13, 92, 852, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGAR ALEXANDER ESPIN', 13, 92, 853, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SONIA RECUERO', 13, 92, 854, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 92, 855, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JOAQUIN GIL', 13, 92, 856, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO CARRETERO', 13, 92, 857, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JUAN ROBLES', 13, 92, 858, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JUAN ROBLES', 13, 92, 859, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 92, 860, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SANTIAGO JOSE PADILLA', 13, 92, 861, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 92, 862, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TUÑAS', 13, 92, 863, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL ALCON', 13, 92, 864, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TUÑAS', 13, 92, 865, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TUÑAS', 13, 92, 866, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 93, 867, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 93, 868, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 93, 869, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 93, 870, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 93, 871, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 93, 872, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 93, 873, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 93, 874, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 93, 875, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 93, 876, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 93, 877, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 93, 878, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 93, 879, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 93, 880, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 93, 881, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO PRATS CHULIA', 13, 93, 882, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 93, 883, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 93, 884, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 93, 885, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 886, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 887, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 888, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 889, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 890, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 891, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 892, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 893, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 894, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 895, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 896, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 897, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 94, 898, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DIONISIO MOLANO ROBLEDO', 13, 94, 885, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 899, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 94, 900, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('VICTOR FERNANDEZ VAYA', 13, 94, 901, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA DEL CONSUELO BRAVO NAVAS', 13, 94, 902, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 95, 903, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 95, 904, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 95, 905, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANGEL LUIS GONZALEZ MARTIN', 13, 95, 906, 'Se usa IA para consultas rápidas (perfectamente realizables desde stack Overflow y otras) porque ofr');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MANUEL ZAPATERO RODRIGUEZ', 13, 95, 907, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JOSE LUIS GONZALEZ ALAMO', 13, 95, 908, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 95, 909, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 95, 910, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DAVID CHISCANO HIDALGO', 13, 95, 911, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MARIA AZAHARA PANADERO RODRIGUEZ', 13, 95, 912, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 96, 913, 'Son cambios muy controlados en una query');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 96, 914, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 915, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 96, 916, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 96, 917, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 96, 918, 'Usada para documentación');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 96, 919, 'Son cambios muy controlados en clases existentes');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 920, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 921, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 922, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 923, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 96, 924, 'Se ha usado para documentar en el Portal del Desarrollo en formato HTML');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 925, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('nan', 13, 96, 926, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 96, 927, 'Es una tarea de pruebas');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 96, 928, 'Son cambios controlados usando una operación ya existente');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 96, 929, 'Son cambios muy controlados');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('RAMON CERRATO ROSA', 13, 96, 930, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 96, 931, 'En esta tarea si que se a utilizado la IA, en el desarrollo de las consultas sql,  y se en la docume');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 96, 932, 'Se a utilizado para la documentación de algunos nuevos métodos');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 96, 933, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 934, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 935, 'Se puede aplicar la IA en los comentarios de código y en refactorizaciones, pero los cambios estaban');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 936, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 921, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL VILA GOMEZ', 13, 96, 925, 'Son cambios muy controlados en una consulta de Base de Datos.');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('MANUEL ZAPATERO RODRIGUEZ', 13, 96, 937, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SERGIO ROMERO MARQUEZ', 13, 96, 938, 'nan');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO LANCHO HERNANDEZ', 13, 96, 939, 'No se ha utilizado porque los cambios consistían en añadir un mensaje ya existente');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL DAVILA ACEDO', 13, 96, 940, 'Solo se utiliza para refactorizar la clase modificada');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JORGE PARRA TOMAS', 13, 96, 941, 'En esta tarea si que se a utilizado la IA, en el desarrollo de las consultas sql');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGARD ALEJANDRO ESPIN', 13, 97, 942, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JUAN ROBLES MATULL', 13, 97, 943, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO CARRETERO', 13, 97, 944, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 97, 945, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 97, 946, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO CARRETERO', 13, 97, 947, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGARD ALEJANDRO ESPIN', 13, 97, 948, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO CARRETERO', 13, 97, 949, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVARO CARRETERO', 13, 97, 950, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SONIA RECUERO', 13, 97, 951, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGARD ALEJANDRO ESPIN', 13, 97, 952, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANTONIO JOSE SEGOVIA', 13, 97, 953, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGARD ALEJANDRO ESPIN', 13, 97, 954, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('EDGARD ALEJANDRO ESPIN', 13, 97, 955, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ALVAR ARGUDO', 13, 97, 956, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JOAQUIN GIL', 13, 97, 957, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANTONIO JOSE SEGOVIA', 13, 97, 958, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('ANTONIO JOSE SEGOVIA', 13, 97, 959, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 97, 960, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('JOAQUIN GIL', 13, 97, 961, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('SONIA RECUERO', 13, 97, 962, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('IGNACIO TUÑAS', 13, 97, 963, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 97, 964, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('YERAY CABRERA', 13, 97, 965, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
INSERT INTO estimacion (owner, proyecto_id, sprint_id, tarea_id, notas) VALUES ('DANIEL ALCON', 13, 97, 966, 'Actualmente solo estamso usando la IA para realizar las HU. En los proximos sprint estamso estudiand');
