INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1799', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1788', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1786', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1785', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1784', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1783', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1782', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1781', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1780', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1778', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1322', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-646', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1034', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1033', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1030', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1019', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1018', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1007', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1006', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-996', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-995', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-994', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-993', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-992', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-991', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-990', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-989', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-987', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-980', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-978', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-971', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-970', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-969', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-936', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-895', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-891', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-851', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-821', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-599', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1244', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1242', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1241', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1234', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1233', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1232', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1230', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1229', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1228', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1227', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1226', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1225', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1224', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1201', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1199', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1146', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1011', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1010', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1009', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-904', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-588', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-36', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-34', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-33', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-32', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-31', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-28', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-26', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-25', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-24', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-23', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-22', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-21', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-20', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-11', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-9', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-8', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-87', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1070', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1069', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1068', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1065', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1064', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1063', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1060', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1058', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1057', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1056', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1055', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1046', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1043', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1042', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1038', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1032', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1031', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1025', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1024', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1023', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1022', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1020', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1003', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1000', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-986', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-985', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-984', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-979', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-885', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1311', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1300', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1299', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1297', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1272', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1271', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1254', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1239', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-66', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-65', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-223', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-224', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-230', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-50', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-86', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-257', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-196', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-268', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-278', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-304', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-265', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-225', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-203', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-219', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-216', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-253', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-307', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1303', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1323', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1324', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1325', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1777', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1818', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1819', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1820', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1821', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1825', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1827', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1830', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1831', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1832', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1833', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1834', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1835', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1836', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1837', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1941', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1940', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1937', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1936', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1932', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1920', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1911', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1910', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1909', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1908', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1901', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1873', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1855', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1330', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1329', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1328', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1327', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1326', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1325', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1324', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1298', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1295', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1284', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1262', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1245', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1150', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1140', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1190', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1189', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1188', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1187', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1184', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1180', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1178', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1113', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1109', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1108', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1107', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1106', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1105', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1101', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1100', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1095', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1092', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1087', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1085', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1084', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1061', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1028', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1027', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1026', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-988', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-761', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-525', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-460', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-457', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-200 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-320 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-215 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-326 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-305 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-306 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-294 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-293 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-295 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-88  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-204 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-67  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-317 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-70  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-69  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-340 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-315 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-316 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-327 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-198 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-197 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-360 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-429 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-445 ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-49  ', 97);
