INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1799 - Fase 1.4 - Generación Modelo de Intercambio', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1788 - Fase 3/3 Migración de la documentación de la wiki al Portal del Desarrollador FW4', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1786 - [QA] Ejecución de Pruebas', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1785 - [QA] Diseño de Pruebas', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1784 - [QA] Cobertura de Pruebas', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1783 - Preparación entornos Git de PMAR', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1782 - Preparación entornos Git de PEXC', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1781 - Lanzar Kiuwan en PMAR sobre CVS', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1780 - Lanzar Kiuwan en PEXC sobre CVS', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1778 - Html: Accesibilidad. No deben aplicarse estilos en el documento HTML', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1322 - Refactorización Gestor Documental Control', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-646 - ProsaGtb en búsqueda de derivada se muestra como en detalle', 86);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1034 - [FRONT] actualizar los translate-service según el dato devuelto como dice la librería para PORTAL', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1033 - [FRONT] actualizar translate-service de la librería para separar métodos según lo que devuelve', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1030 - Error al borrar un grupo de usuarios', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1019 - Verificar que un grupo de usuarios no está excluido al aplicar política que utilice un grupo de usuarios', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1018 - Añadir configuración de prosaedi a proyecto WFBT', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1007 - [QA] Pruebas GIT Sprint 20', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1006 - Baja de proceso batch WFBTEXIH y limpieza de código - PRWF', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-996 - [QA] Diseño de Pruebas', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-995 - [QA] Cobertura de Pruebas', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-994 - Configuración Entorno GIT', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-993 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Ramon', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-992 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Alvaro', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-991 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Jorge', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-990 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Vila', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-989 - Revisión de la documentación en el Portal de desarrollo', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-987 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Davila', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-980 - [FRONT] La ordenación en las tablas filtradas falla en Firefox', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-978 - Error en el servicio de Consulta de datos caso - pantalla blanca con un caso de SARA en SG01', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-971 - [FRONT] Cambiar el servicio de persistencia en btal para utilizar el de la libreria', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-970 - [FRONT] Cambiar el servicio de persistencia en portal para utilizar el de la libreria', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-969 - [FRONT] Añadir el servicio de persistencia de datos a la libreria', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-936 - El proceso batch escoba de WFBTGLEX atascado por escuchadores pendientes de casos cancelados', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-895 - Baja de proceso batch WFBTEXIH y limpieza de código', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-891 - Dedicación de un usuario en una unidad funcional', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-851 - Servicio de gestión de Límites de carga para una unidad funcional', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-821 - Administrar ámbitos de gestión', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-599 - [FRONT] Mostrar Filtros Aplicado en los filtros por tipo de tarea en la bandeja de supervisor', 87);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1244 - Modificación en componente de pruebas de SGPF de servicios de intermediación SVID, SCID, SVDR', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1242 - Modificación en API SCID, SVID, SVDR para corregir NullPointerExcepcion en la clase ParqSCIDDatosMockDao', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1241 - Scripts asociados a corrección de reglas críticas BSER', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1234 - [QA] Cobertura de Pruebas', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1233 - [QA] Ejecución de Pruebas', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1232 - [QA] Diseño de Pruebas', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1230 - Fase 2/2 Revisar y migrar al Portal del desarrollo artículo InfraSMS', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1229 - Fase 2/2 Revisar y migrar al Portal del desarrollo artículos utilidades GENDOC y GENDOCASIN', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1228 - Configuración Entorno GIT - Cristian', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1227 - Configuración Entorno + Migración de los desarrollos de la 9.0.4 a GIT - Benjamin', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1226 - Configuración Entorno Trabajos + Migración de los desarrollos de la 9.0.4 a GIT - Azahara', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1225 - Configuración Entorno Trabajo + Migración de los desarrollos de la 9.0.4 a GIT - David', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1224 - Configuración Entorno Trabajo + Migración de los desarrollos de la 9.0.4 a GIT - Angel', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1201 - Revisar mapeo de entorno-endpoint en GSPRCOAP', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1199 - [FRONT] Quiero poder realizar búsqueda avanzada por todos los campos de trabajos y planificaciones en la bandeja de procesos', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1146 - GSPRCOAP - Quiero poder consultar el organismo asociado de la aplicación', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1011 - Modificar respuesta API Variables de Negocio para variables no obligatorias', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1010 - Incluir nueva propiedad en el alta de una variable de negocio GSPR', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1009 - Devolver URL completa ', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-904 - API SMS - quiero poder especificar opciones de envío', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-588 - Adaptar los nombres de los entornos y añadir nuevos', 88);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-36 - [FRONT] - Desarrollar pantalla de negocio', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-34 - Refinamiento Sprint 2', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-33 - [QA] Ejecución de Pruebas', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-32 - [QA] Diseño de Pruebas', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-31 - [QA] Cobertura de Pruebas', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-28 - [FRONT] Investigar la POC de pintado equipo Front', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-26 - [FRONT] Logica de Negocio la pantalla', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-25 - [FRONT] Pintado del formulario con las diferentes validaciones de tipo tarea', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-24 - Guardado de Admin tarea detalle', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-23 - Combos de fecha proceso y expediente', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-22 - Combo estado de tramites', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-21 - Validar el borrado de tablas relacionado con tareas', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-20 - Consulta tipo Servicio WF', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-11 - Desarrollar pantalla de negocio', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-9 - [FRONT] Definición de los datos generales de las tareas', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-8 - Desarrollar pantalla de selección de categoría y tipo de tarea con filtrado y ordenamiento - Back: 8 / Front: 3', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-87 - Gestión de excepciones componente aplicación back', 89);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1070 - Controlar excepciones de asignaciÃ³n cuando no encuentra polÃ­tica', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1069 - Tomar en cuenta datos del tipo texto largo entre la informaciÃ³n de disparos global', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1068 - Error al aplicar la política de Menor Carga de Usuario - guardar en USRPOLITICASNODO', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1065 - WFBTRSET - Proceso batch de resetear total tarea asignada a diario ', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1064 - Limite carga: trigger de actualizar total tareas diario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1063 - [FRONT] Implementar el ModalService en la librería', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1060 - [FRONT] Implementar las pills scrollables', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1058 - Inactivar servicios WFAPLICA', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1057 - Modificar el nombre de la columna Dedicación', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1056 - Apdatación de VIPR a la pasarela', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1055 - Error al asignarme o desasignarme una tarea después de despacharla', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1046 - [FRONT] Mejorar el persistance de la librerí­a.', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1043 - [FRONT] Sustituir el SelectionList actual por el de la librerí­a PORTAL', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1042 - [FRONT] Pasar el SelectionList a la librería', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1038 - Pruebas y revisión de cálculo de fecha lí­mite: modelo flujos vs modelo antiguo', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1032 - WFBTHIST - registrar incidencia más informativa con error de eliminar documento Portafirmas', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1031 - Enví­o a Portafirmas - tratar documentos que no existen en el gestor documental', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1025 - Polí­tica MenCargaUF - valida lí­mite carga usuario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1024 - Polí­tica MenCargaGr  - valida límite carga usuario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1023 - Polí­tica AsigDirUF - valida lí­mite carga usuario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1022 - Modificación del proceso WFAPEEUS para la exclusión de usuarios de la unidad funcional', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1020 - Utilidad: GEID en el servicio XV1F4500 (VALIDAR_SERVICIO_UTILIDAD )', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1003 - Modelo flujo: corregir errores de validación a la hora de finalizar tarea', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1000 - El proceso batch WFBTRSRV ignora las tareas externas reservadas', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-986 - Política AsigTarSc - valida lí­mite carga usuario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-985 - Autoasignación - valida lí­mite carga usuario', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-984 - Servicio de asignación manual de tarea - validar límite carga', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-979 - Operación para validar lí­mite de carga usuario al asignar tarea', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-885 - Añadir información a las propiedades y polí­ticas de bandeja de supervisor', 90);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1311 - Problemas sacar informes - no se tiene en cuenta cuando se indica color o blanco y negro', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1300 - Declarar asociación entre proceso GSPRBIUS y la utilidad API-INFORME-USU ', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1299 - Kiuwan Subir la nota de BPRO', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1297 - Actualizar recubrimiento Prosa de SVDR para contemplar nuevo parámetro de selección en el consentimiento', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1272 - Arreglar el entorno de GIT', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1271 - Alinear CVS con GIT', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1254 - Revisión de errores y dudas con las nuevas operaciones con carpetas del API de SGDA', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1239 - Fase 1/? Obtener listado de clases que determinan el uso de cada utilidad', 91);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-66 - Mapeos para resolver  Tarea WF', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-65 - Mapeos de tipo Expediente y procedimiento', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-223 - Fase 2/2 Combos de fecha expediente y procedimiento', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-224 - Fase 2/2 Combo operaciones por tipo de operacion', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-230 - Fase 2/2 Combo de ciudadano expediente y procedimiento', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-50 - Desarrollar seccion para definir el "Ambito del evento" de las Tareas de Eventos', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-86 - Cambio d ealcance: Modificacion de los mapeos ETRA', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-257 - (BACK)Mapeos de tipo Nodo para resolver el Servicio/Batch', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-196 - Mapeos de tipo Expediente y  Procedimiento para resolver el servicio/batch', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-268 - (FRONT)Mapeos de tipo Nodo para resolver el servicio/batch', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-278 - Generar documentacion Sprint1', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-304 - analaisis y generacion de contrato swagger entre front y back', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-265 - Validar el borrado de tablas relacionado con tareas', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-225 - (QA) Fase 2/2 Combo estado de tramites', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-203 - (QA) Fase 2/2 Desarrollo pantalla de negocio', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-219 - (QA) Desarrollo pruebas automaticas Sprint1', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-216 - (QA) Pruebas automaticas Sprint1', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-253 - (QA) Capturar los HTML geenrados en PDPR', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-307 - (QA) ejecucion pruebas automaticas', 92);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1303 - Realización de pruebas (Equipo de Desarrollo) de la entidad documento con GD y de la entidad documento en BBDD', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1323 - Refactorización Gestor Documental LIBA', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1324 - Se repite el nombre de las zonas para las derivadas del alta y la modificación', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1325 - Plugin¿? - Solo aparece el placeholder y   la Exp.Regular en los xsl de busqueda cuando deberia de verse tambien en los de alta y modificación en los ProsaEmail y Prosatelefono', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1777 - Mover uso ParqOpNegAplicacionProsaHelper por parte de PexcAccConsultaPagAplicaciones a PEXC', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1818 - Configuración de los Equipos de los Tester', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1819 - Revisión de las tareas del Backlog de Jira', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1820 - Reestructurar el Teams de ProsaGen', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1821 - Fase 2/2 Refactorización Gestor Documental Control', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1825 - Crear un roadmap de lo que falta por desarrollar del API PDPR.', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1827 - No se visualizan descripciones para ProsaGTB', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1830 - Fase 4/4 Migración de la documentación de la wiki al Portal del Desarrollador FW4', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1831 - Fase 2/2 - Html: Accesibilidad. No deben aplicarse estilos en el documento HTML', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1832 - Lanzar Kiuwan PEXC', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1833 - Lanzar Kiuwan PMAR', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1834 - Lanzar Kiuwan PGEN', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1835 - Lanzar Kiuwan LIBA', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1836 - Lanzar Kiuwan EDIM', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1837 - Fase 1.5 - Generación Modelo de Intercambio', 93);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1941 - Generar Site Prosagen', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1940 - Configuración de los Equipos de los Tester', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1937 - ProsaBoolean: En la pantalla de busqueda no se muestra la etiqueta para los campos con valores constantes y da error al buscar java.lang.NullPointerException:null', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1936 - Listas: Implementar en  Alta y Modificación en el NMN', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1932 - No se muestran los valores para prosaBoolean ni en la tabla de resultados ni en el detalle', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1920 - Maestro detalle - No se refleja lo que esta diseñando en el plugin en el código generado para PROSAGTB', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1911 - Revisar si en la pantalla del Alta del MAESTRO, no se puede configurar si se desea que una pantalla derivada se muestre por campo selección o pantalla de consulta', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1910 - No funcionan las validaciones por operadores', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1909 - No aparece un asterisco en los atributos ProsaBoolean cuando son requeridos', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1908 - Validaciones en los campos de ProsaEmail ( Tooltip,Placeholder,Exp.Regular,Mensaje )', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1901 - Analizar el estado final del servicio REST Prosa', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1873 - Establecer una ruta definitiva a los recursos de las ayudas de Pros@Help.', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1855 - Borrar las clases existentes de la Infraestructura Privada que son usadas por PEXC', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1330 - Comprobar que la gestión y creación de nuevas de excepciones funciona generando código fuera del CURS', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1329 - Listas de valores ProsaString: En búsquedas', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1328 - En la consulta de Detalle no se toman los valores de escritorio configurados al momento de ejecución', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1327 - ProsaString: En la pantalla de busqueda no se muestra la etiqueta para los campos con valores constantes y da error al buscar java.lang.NullPointerException:null', 94);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1326 - Fase 2/2 Revisión reglas Críticas y Aspirantes - GSPR', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1325 - Fase 2/2 Actualizar recubrimiento Prosa de SVDR para contemplar nuevo parámetro de selección en el consentimiento', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1324 - Contemplar dependencia de utilidad FIRMA_BIO de FSERVIDOR ya que se hace sellado en el servidor', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1298 - Recubrimiento de nuevas operaciones de Registro Presencial', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1295 - [FRONT] Ajustes y mejoras para BPRO', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1284 - Mostrar en GSPRCOAP cuando una aplicación está en estado de baja ', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1262 - Revisión reglas Críticas y Aspirantes - BSER', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1245 - Revisar funcionamiento SCAN por Extranet', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1150 - GSPR - ParqSpmOutputFormatExceptionen el servicio XV20Y101', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1140 - Como responsable de aplicación quiero poder especificar si quiero que se vea el logo en la cabecera y qué logo', 95);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1190 - Error, graba nodo incorrecto en BBDD', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1189 - Eliminar mensaje cuando se accede a la Gestión de grupos de usuarios', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1188 - Exclusión de usuarios Usuario anterior- UsrAnterio política estática', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1187 - Modelo flujos: tipo nodo flujo parada', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1184 - Añadir Información adicional al servicio Exclusión de usuario para políticas', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1180 - Servicio Asignación manual de tareas por usuario - valida límite carga usuario', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1178 - El servicio de Asignación Manual de Usuarios (XV1F4500) está validando los usuarios excluidos por la política secuencial', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1113 - Exclusión de usuarios Usuario con menor carga de trabajo de la unidad funcional', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1109 - Exclusión de usuarios con menor carga de un grupo', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1108 - Exclusión de usuarios Grupo de usuarios con condiciones', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1107 - Exclusión de usuarios para reparto de Asignación al usuario anterior', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1106 - Componente de prueba: API Workflow hayMisTareasBloqueadasPorGrupo ', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1105 - Exclusión de usuarios para reparto de casos por secuencia por tipo de tarea', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1101 - Modelo flujos: pruebas de Tarea WF y tarea automática', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1100 - Modelo flujos: tarea automática de pruebas', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1095 - API: hayMisTareasBloqueadasPorGrupo para sustituir la operación HAY_TABLGR', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1092 - Error en el API de dameInfoCaso() a la hora de recuperar caso históricos con expediente', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1087 - Modelo flujos: tarea automática', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1085 - Modelo flujos: tipo nodo Tarea WF', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1084 - Corrección de cálculo de fecha límite: modelos flujos vs tradicional', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1061 - [FRONT]  Implementar SelectionModal en la Librería con el nuevo ModalService', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1028 - Política CondiGrupo - valida límite carga usuario', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1027 - Política UsrAnterio  - valida límite carga usuario', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-1026 - Política UsrNodosAn - valida límite carga usuario', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-988 - Fase 2/2 - [FRONT] Implementar mejoras detectadas para el componente Tabla para mayor compatibilidad con otros proyectos de la GISS', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-761 - [FRONT] Incluir el componente de Tabs en la libería', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-525 - Mensaje incorrecto en la asignación de tareas y casos', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-460 - ProsaEDI - permitir exportar procedimiento si no pertenece a asociaciones erróneas', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF-457 - Permitir inactivar un procedimiento sin pasar los casos al historico', 96);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-200  - Componente Excepciones                                                                      ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-320  - Generar script con PRID de los datos de al aplicacion PDPR                                  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-215  - Pantalla listado de script falta columna acciones                                           ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-326  - Ajustar la cantidad de pasos pro pagina en el listado de pasos de pasos de un proceso batch ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-305  - Restricciones de tareas de inicio en el portal                                              ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-306  - Flexibilidad en la definicion de nombres de tareas                                          ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-294  - validaciones en los datos especificos de la tarea                                           ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-293  - Modificacion el servicio de pruebas Pantalla de datos d ela tarea                           ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-295  - Modificacion de la pantalla de datos generales: Mostrar en consulta de casos                ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-88   - Diferenciasr los datos de expediente y los datos de procedimiento                           ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-204  - Gestion de excepciones componente aplicacion                                                ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-67   - Mapeos para resolver el nodo                                                                ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-317  - Eliminar procedimiento ETRA asociado al Procedimiento                                       ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-70   - Mapeos para etapas                                                                          ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-69   - Mapeos Anexar documentos                                                                    ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-340  - Añadirpaginacion en listado Excepciones                                                     ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-315  - Revisar validaciones y mensajes de error en componente Excepciones                          ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-316  - Revisar validaciones  y mensajes de error en compoente batch                                ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-327  - Verificar el Rol del usuario antes demostrar la primera pantalla                            ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-198  - Mapeos de resolver el nodo                                                                  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-197  - Mapeos para resolver el tarea WF                                                            ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-360  - Ejecucion d epruebas automaticas sprint2                                                    ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-429  - Eliminacion de referencias  de mapeos datos fe procedimiento o expedientes                  ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-445  - Cambios de clave primaria de tabla TIPO_DATO:MAPEO                                          ', 97);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-49   - Ejecucion automatica para el tipo TAREA                                                     ', 97);
