INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-21', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-22', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-22', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-23', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T49', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-SP16', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-SP17', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- PDPR-Fase 2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T52', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T53', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- PROSAGEN-22', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-23', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-25', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-16', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-17', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-16', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Arquitectura-24', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-26', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDAU-Portales-T55', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM31', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM30', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-20', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-24', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDCF-PDCF', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR-4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-23', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-24', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Digitalización-T4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDCF-22', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR-AUTO-4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDAU-Portales-T54', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-27', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM32', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-25', '2');
