INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 821 - Gestión de ambitos', 98);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 985  - Asignacion - valida limite carga usuario', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 979 - Operacion para validar limite de carga usuario al asignar tarea', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1055 - Error al asignarme desasignarme una tarea despues de despacharla', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 984 - Servicio de asignacion manual de tarea- validar limite carga', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDAU-01 - Indicadores KPIs', 102);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('SDSS54884 - Grafito: componente BUTTON (2)', 102);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPR- Frontent - Validar eliminar expediente', 105);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR - 10 - Datos especificos de las tareas.', 105);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POIT55217 - Pruebas de versión v3.54', 106);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55300 - Rediseño PDEV S104', 107);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('  - Manual Prosa - Bandeja de Tareas', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('AUTR004 - Workflow - Procedimientos - Datos del Procedimiento - Validación Botón Guardar Campos obligatorios', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN 646 - PROSAGTB en busqueda derivada se muestra detalle', 108);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1108 - Asignacion - valida limite carga usuario', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1028 - validar limite carga usuario - politica condigrupo', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1101 - modelo flujos', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1026 - politica usrnodos an- valida limite carga usuario', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1138 - añadir informacion adicional al servicio de excluison de usuario para politicas', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1105 - exclusion de usuarios par areparto de casos por secuenciua por tipo tarea', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1107 - Exclusion de usuarios para reparto de asignacion al usuario anterior', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1085 - Nuevo modelo de flujos', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 536 -  ', 111);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 537 -  ', 112);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1269 - Cobertura de pruebas ', 115);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POSJ55327 - Pruebas búsqueda', 116);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('- - Gestion de grupos', 118);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-863 - Cobertura de pruebas ', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1248 - Proceso batch WFBTAGST- calcular UF con menor carga por ambito de gestion', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1208 - Motor workflow- crear tareas siguiente con ambito de gestion', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-838 - Consulta de Listados y Consulta Histórico de Listados', 117);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDCFAUTO - Automatizacion de Pruebas', 121);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH - Automatizacion de Pruebas', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-68 - Cobertura de pruebas ', 122);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMAAUTO - Documentación del script ', 125);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEFONPEN-1808 - Cobertura de pruebas ', 126);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NMDEAUTO - Automatizacion de Pruebas', 125);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF -1287 - Pruebas automaticas Modelo de Flujo ', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPRAUTO - Automatizacion de Pruebas', 127);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PORTALESAUTO - Automatizacion de Pruebas', 116);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('RGID52224 - Pruebas de regresión de GISS Digital', 128);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55404 - Evolución PDEVXplora', 128);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1339 - Cobertura de pruebas ', 129);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1185 - API : dameInfoCasosArchivados', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1250 - Trigger de BBDD para actualizar peso tarea y procedimiento almacenado para procesar tareas existentes sin peso.', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-2018 - Cambios en formatos de fechas-horas admitidos', 131);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-906 - Cobertura de pruebas ', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1349 - Cobertura de pruebas ', 129);
