INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-21', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-22', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-22', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-23', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T49', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-SP16', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-SP17', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- PDPR-Fase 2', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T52', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Plataformas Digitales-T53', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- PROSAGEN-22', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-23', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-25', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-16', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-17', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('FDAR-16', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Arquitectura-24', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-26', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDAU-Portales-T55', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM31', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM30', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('RRHH-20', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA- WORKFLOW-24', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDCF-PDCF', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR-4', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-23', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-24', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Digitalización-T4', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDCF-22', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR-AUTO-4', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDAU-Portales-T54', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('NAUA-27', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('IBASE-TM32', 14);
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PROSA-PROSAGEN-25', 14);
