INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 821', 98);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 985 ', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 979', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1055', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 984', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDAU-01', 102);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('SDSS54884', 102);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPR- Frontent', 105);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR - 10', 105);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POIT55217', 106);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55300', 107);
INSERT INTO tarea (descripcion, sprint_id) VALUES (' ', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('AUTR004', 99);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN 646', 108);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1108', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1028', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1101', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1026', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1138', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1105', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1107', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1085', 109);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 536', 111);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 537', 112);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1269', 115);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POSJ55327', 116);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('-', 118);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-863', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1248', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1208', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-838', 117);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDCFAUTO', 121);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-68', 122);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMAAUTO', 125);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEFONPEN-1808', 126);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NMDEAUTO', 125);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF -1287', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPRAUTO', 127);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PORTALESAUTO', 116);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('RGID52224', 128);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55404', 128);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1339', 129);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1185', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1250', 120);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-2018', 131);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-906', 119);
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1349', 129);
