INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 821', '8');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 985 ', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 979', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1055', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 984', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDAU-01', '12');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('SDSS54884', '12');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-183', '13');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDENXDE-218', '14');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPR- Frontent', '15');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR - 10', '15');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POIT55217', '16');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55300', '17');
INSERT INTO tarea (descripcion, sprint_id) VALUES (' ', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('AUTR004', '9');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN 646', '18');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1108', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1028', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1101', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1026', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1138', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1105', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1107', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF - 1085', '19');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 536', '21');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH 537', '22');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROARQ-1140', '24');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1269', '25');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('POSJ55327', '26');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1308', '27');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1368', '28');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('-', '28');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1310', '27');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-863', '29');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1248', '30');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1208', '30');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-838', '27');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDCFAUTO', '31');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH', '29');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPDPR-68', '32');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1827', '33');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-1327', '34');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NOMAAUTO', '35');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEFONPEN-1808', '36');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('NMDEAUTO', '35');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF -1287', '30');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDPRAUTO', '37');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PORTALESAUTO', '26');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('RGID52224', '38');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('PDEV55404', '38');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1191', '27');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1339', '39');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1176', '27');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEINBASE-1194', '40');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1185', '30');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROWRF 1250', '30');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEPROGEN-2018', '41');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DEDEXSCH-906', '29');
INSERT INTO tarea (descripcion, sprint_id) VALUES ('DENAUA-1349', '39');
