INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('GISS - Crear HU', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Code Documentation Helper', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - BBDD-Sql', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Code Guide', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Documentación Técnica', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pte de seleccionar Prompt', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documuentar', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T01_Excel de Cobertura', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T02_Diseño de Casos de Prueba', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T03_Combinación de Datos de Prueba', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T04_Plan de Pruebas de Regresión', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T05_Estrategia de pruebas', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T06_Scripts de Automatización', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Información para Pruebas (sin Prompt)', 15);
