INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 1);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 2);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 3);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 4);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 5);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 6);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 7);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('GISS - Crear HU', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Code Documentation Helper', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - BBDD-Sql', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Code Guide', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Giss - Documentación Técnica', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pte de seleccionar Prompt', 8);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 9);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 10);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 11);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 13);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 12);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 15);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 16);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 17);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 18);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 19);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 20);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 21);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Crear HU', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Documentar', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Refactorizar', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Comprender Codigo Fuente', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Analisis Desa APIs', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Unitarias', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Pruebas Funcionales', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 22);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 23);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 24);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 25);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T01_Excel de Cobertura', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T02_Diseño de Casos de Prueba', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T03_Combinación de Datos de Prueba', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T04_Plan de Pruebas de Regresión', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T05_Estrategia de pruebas', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('T06_Scripts de Automatización', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('Información para Pruebas (sin Prompt)', 14);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 27);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 28);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 26);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 29);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 30);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 31);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 32);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 33);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 34);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 35);
INSERT INTO prompt (prompt, proyecto_id) VALUES ('nan', 36);
