INSERT INTO proyecto (nombre) VALUES ('ABDV');
INSERT INTO proyecto (nombre) VALUES ('STAG');
INSERT INTO proyecto (nombre) VALUES ('GDLC2');
INSERT INTO proyecto (nombre) VALUES ('DEVOPS');
INSERT INTO proyecto (nombre) VALUES ('DEVOPS Soporte');
INSERT INTO proyecto (nombre) VALUES ('CIDIGA');
INSERT INTO proyecto (nombre) VALUES ('CIGDOC');
INSERT INTO proyecto (nombre) VALUES ('CIDCLO');
INSERT INTO proyecto (nombre) VALUES ('EVsCaching');
INSERT INTO proyecto (nombre) VALUES ('nan');
INSERT INTO proyecto (nombre) VALUES ('FDAR');
INSERT INTO proyecto (nombre) VALUES ('IBase');
INSERT INTO proyecto (nombre) VALUES ('APNA');
INSERT INTO proyecto (nombre) VALUES ('Testing');
INSERT INTO proyecto (nombre) VALUES ('NAUA');
INSERT INTO proyecto (nombre) VALUES ('NAUF');
INSERT INTO proyecto (nombre) VALUES ('DEPOLIFE');
INSERT INTO proyecto (nombre) VALUES ('DESACITA');
INSERT INTO proyecto (nombre) VALUES ('DESACEIN');
INSERT INTO proyecto (nombre) VALUES ('DEDIGRAF');
INSERT INTO proyecto (nombre) VALUES ('DEPINTRA');
INSERT INTO proyecto (nombre) VALUES ('DEPINTE ');
INSERT INTO proyecto (nombre) VALUES ('ProsaGen');
INSERT INTO proyecto (nombre) VALUES ('WF');
INSERT INTO proyecto (nombre) VALUES ('Arquitectura');
INSERT INTO proyecto (nombre) VALUES ('PDPR');
INSERT INTO proyecto (nombre) VALUES ('PROSA- WORKFLOW');
INSERT INTO proyecto (nombre) VALUES ('Plataformas Digitales');
INSERT INTO proyecto (nombre) VALUES ('PROSA- PDPR');
INSERT INTO proyecto (nombre) VALUES ('PROSA- PROSAGEN');
INSERT INTO proyecto (nombre) VALUES ('RRHH');
INSERT INTO proyecto (nombre) VALUES ('PDAU-Portales');
INSERT INTO proyecto (nombre) VALUES ('IBASE');
INSERT INTO proyecto (nombre) VALUES ('PDCF');
INSERT INTO proyecto (nombre) VALUES ('PROSA-PROSAGEN');
INSERT INTO proyecto (nombre) VALUES ('Digitalización');
INSERT INTO proyecto (nombre) VALUES ('PDPR-AUTO');
