INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP7', '1');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP0', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP0', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP0', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP0', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP1', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP2', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP3', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP4', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP5', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP6', '2');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '3');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP40', '5');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP41', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP41', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP41', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP41', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP42', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP43', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP44', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP45', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP46', '4');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP83 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP91 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP05 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP84 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP92 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP06 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP93 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP85 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP07 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP86 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP94 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP08 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP87 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP95 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP09 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP96 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP96 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10 - NMDE', '8');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP88 - NOTE', '6');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP97 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP97 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP97 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP97 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP97 - GDOC', '7');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP9', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP10', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP11', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP12', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP12', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP12', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP12', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '9');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP13', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP14', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP15', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP18', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP19', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Octubre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Noviembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Diciembre', '12');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP20', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP21', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '13');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '14');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP24', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 20', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 20', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 21', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 21', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Srpint 22', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 23', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 23', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Sprint 24', '16');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('nan', '10');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 106', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 106', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 106', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPOLIFE 107', '17');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA 100', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA S/P', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA S/P', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA S/P', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA S/P', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACITA S/P', '18');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACEIN 115', '19');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACEIN 116', '19');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACEIN 115', '19');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DESACEIN 116', '19');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 8', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 8', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 8', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 10', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 9', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEDIGRAF 10', '20');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA 108', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA 108', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTRA S/P', '21');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE 102', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE 102', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE 102', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE S/P', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('DEPINTE 102', '22');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN22', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 21', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ22', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR01', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 22', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ23', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR02', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN23', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PGEN24', '23');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('ARQ24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('WF 23', '24');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDPR03', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('21', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T49', '28');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T49', '28');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('SP17', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Fase 2', '29');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('Fase 2', '29');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T52', '28');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T53', '28');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '30');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('25', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('16', '31');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('17', '31');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('21', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('16', '11');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '25');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('26', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T55', '32');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM31', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM30', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM30', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM31', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('20', '31');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM31', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('PDCF', '34');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('20', '31');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('4', '26');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('23', '35');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '35');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T4', '36');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('22', '34');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T4', '36');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('4', '37');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T55', '32');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T54', '32');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('T54', '32');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM31', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('27', '15');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM31', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('TM32', '33');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('24', '27');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('25', '35');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('4', '37');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('20', '31');
INSERT INTO sprint (nombre, proyecto_id) VALUES ('27', '15');
